/**
 * More Central Government Welfare Schemes Dataset (part 2)
 * [external_id, title, category, tag, description, benefit, eligibility, source_url]
 */
export const CENTRAL_SCHEMES_PART2 = [
  // ── AGRICULTURE EXTENDED ──────────────────────────────────────────────────
  ['kisan-sampada-coldchain', 'Integrated Cold Chain & Value Addition Infrastructure', 'Agriculture', 'Cold Chain', 'Creates integrated cold chain facilities and primary processing centres for farm produce.', '₹10 Crore grant per project for cold chain infrastructure', 'FPOs, cooperatives, agri-entrepreneurs', 'https://mofpi.gov.in'],
  ['agri-marketing-infra', 'Agricultural Marketing Infrastructure (AMI) Scheme', 'Agriculture', 'Market Infrastructure', 'Creates marketing infrastructure like godowns, cold storages and market yards in rural areas.', 'Capital subsidy up to 25% on marketing infrastructure', 'Farmers, cooperatives and agricultural entrepreneurs', 'https://agricoop.gov.in'],
  ['sub-mission-agri-extension', 'Sub-Mission on Agricultural Extension', 'Agriculture', 'Extension', 'Strengthens farmer extension services through Kisan Call Centres, e-choupals and demonstrations.', 'Free expert advice, demonstrations and farm schools', 'All farmers', 'https://agricoop.gov.in'],
  ['millets-mission', 'National Millet Promotion Programme (Shree Anna)', 'Agriculture', 'Millets', 'Promotes millet cultivation, processing, and market linkages to boost nutritious coarse cereals.', 'Subsidy on millet seeds, processing units and procurement support', 'Millet-growing farmers and FPOs', 'https://agricoop.gov.in'],
  ['pulses-programme', 'National Programme on Pulses Development', 'Agriculture', 'Pulses', 'Increases pulse production through certified seed distribution and pulse villages.', 'Subsidised pulse seeds and cluster demonstration support', 'Pulse-growing farmers in notified districts', 'https://agricoop.gov.in'],
  ['sugarcane-subsidy', 'Sugarcane Development and Welfare Scheme', 'Agriculture', 'Sugarcane', 'Improves sugarcane productivity and ensures remunerative cane prices and farmer welfare.', 'Subsidised cane seeds, drip irrigation and transport support', 'Sugarcane farmers', 'https://agricoop.gov.in'],
  ['tobacco-board', 'National Tobacco Control and Development Scheme', 'Agriculture', 'Tobacco', 'Support for tobacco growers for alternative crops and quality improvement under ITC guidance.', 'Technical and marketing support for registered growers', 'Registered tobacco growers', 'https://tobaccoboard.com'],
  ['cotton-mission', 'National Cotton Mission', 'Agriculture', 'Cotton', 'Improves cotton productivity and quality through hybrid seeds, pest management and mechanisation.', 'Subsidised high-density planting and extension support', 'Cotton farmers', 'https://nfsm.gov.in'],
  ['coffee-board', 'Coffee Development Programme', 'Agriculture', 'Coffee', 'Financial assistance for replantation, irrigation, and quality upgradation of coffee gardens.', 'Replantation subsidy up to 40% and irrigation support', 'Registered coffee growers', 'https://coffeeboard.gov.in'],
  ['rubber-board', 'Rubber Plantation Development Scheme', 'Agriculture', 'Rubber', 'New rubber plantation and replantation assistance for small growers in traditional and non-traditional areas.', 'Planting material subsidy up to ₹28,000 per hectare', 'Small rubber growers', 'https://rubberboard.org.in'],
  ['spices-board', 'Spices Development Programme', 'Agriculture', 'Spices', 'Cluster-based development of spices production with quality planting material and processing.', 'Subsidy on spices processing and extension support', 'Spice growers and processors', 'https://indianspices.com'],
  ['organic-agri-cluster', 'Mission Organic Value Chain Development in NE (MOVCD-NER)', 'Agriculture', 'Organic Farming NE', 'Organic value chain development for farmers in North Eastern states with certification support.', '₹25,000-30,000 per hectare organic conversion support', 'Farmers in North Eastern states forming FPOs', 'https://agricoop.gov.in'],

  // ── ANIMAL & ALLIED EXTENDED ──────────────────────────────────────────────
  ['poultry-ventilation', 'Poultry Venture Capital Fund', 'Agriculture', 'Poultry', 'Promotes poultry farming through capital subsidy on broiler and layer units.', 'Capital subsidy up to 25% on poultry projects', 'Individual farmers, SHGs and poultry entrepreneurs', 'https://dahd.nic.in'],
  ['piggery', 'Pig Development Scheme', 'Agriculture', 'Piggery', 'Promotes piggery development, especially in NE states, with quality breed improvement.', 'Subsidy on pig units and breeding stock', 'Pig farmers and rural households', 'https://dahd.nic.in'],
  ['sheep-goat', 'Sheep and Goat Development', 'Agriculture', 'Sheep & Goat', 'Improves small ruminant productivity through breed improvement and health coverage.', 'Subsidy on sheep/goat units and rams support', 'Small and marginal farmers', 'https://dahd.nic.in'],
  ['fodder-mission', 'National Mission on Fodder and Feed', 'Agriculture', 'Fodder', 'Ensures fodder security through cultivation of high-yielding fodder and silage making.', 'Fodder seed subsidy and silage machinery support', 'Livestock-owning farmers', 'https://dahd.nic.in'],
  ['fish-seed', 'Fish Seed and Hatchery Development', 'Agriculture', 'Fisheries', 'Strengthens fish seed production through hatchery modernisation and quality seed distribution.', 'Subsidy on hatcheries and fish seed production', 'Fish farmers and hatchery operators', 'https://dof.gov.in'],
  ['mariculture', 'Mariculture and Seaweed Farming Scheme', 'Agriculture', 'Mariculture', 'Promotes coastal mariculture, sea cage farming and seaweed cultivation for coastal livelihoods.', 'Subsidy up to 60% on sea cage and seaweed units', 'Coastal fishers and self-help groups', 'https://pmmsy.dof.gov.in'],
  ['beekeeping', 'Beekeeping – Honey Mission', 'Agriculture', 'Beekeeping', 'National Beekeeping & Honey Mission for scientific beekeeping and honey processing clusters.', '₹500 subsidy per bee colony with training', 'Small farmers and beekeeping entrepreneurs', 'https://nbb.gov.in'],

  // ── ENERGY EXTENDED ───────────────────────────────────────────────────────
  ['solar-water-pumping', 'Solar Water Pumping Programme', 'Energy', 'Solar Pumps', 'Standalone and grid-connected solar water pumps for irrigation and drinking water.', '40-60% subsidy on solar pumps for farmers', 'Individual farmers and groups in rural areas', 'https://mnre.gov.in'],
  ['solar-street-light', 'Solar Street Light Programme', 'Energy', 'Solar Lighting', 'Solar street lighting for villages, hamlets and areas without reliable power.', 'Subsidised solar street lights for panchayats', 'Rural areas and public institutions', 'https://mnre.gov.in'],
  ['national-wind-solar', 'Offshore and Hybrid Wind-Solar Policy', 'Energy', 'Hybrid Renewables', 'Promotes wind-solar hybrid and offshore projects with grid integration support.', 'Policy incentives for hybrid renewable projects', 'Renewable energy developers', 'https://mnre.gov.in'],
  ['waste-to-energy', 'Waste to Energy Programme', 'Energy', 'Waste Management', 'Sets up waste-to-energy plants converting municipal solid waste into power.', 'Financial support for waste-to-energy projects', 'Municipalities and project developers', 'https://mnre.gov.in'],
  ['cookstoves', 'National Improved Cookstove Programme', 'Energy', 'Clean Cooking', 'Promotes energy-efficient biomass cookstoves to reduce smoke and fuel use in rural kitchens.', 'Subsidised improved cookstoves for rural households', 'Rural households using traditional chulhas', 'https://mnre.gov.in'],

  // ── HEALTHCARE EXTENDED ───────────────────────────────────────────────────
  ['national-cancer', 'Strengthening of Tertiary Cancer Care Facilities (NPCDCS Cancer)', 'Healthcare', 'Cancer Care', 'Upgrades tertiary cancer care with state cancer institutes and RCCs in every state.', 'Regional cancer centres and affordable cancer treatment', 'Cancer patients referred through public health system', 'https://ncdindia.org'],
  ['npcch', 'National Programme for Prevention & Control of Deafness', 'Healthcare', 'Hearing', 'Screening, early identification and rehabilitation of hearing impairment across all ages.', 'Free hearing screening and ear care services', 'All citizens, especially newborns and children', 'https://nhm.gov.in'],
  ['npntcp', 'National Programme for Prevention & Control of Blindness', 'Healthcare', 'Eye Care', 'Reduces blindness through free cataract surgeries, eye banks and vision screening.', 'Free eye check-ups and cataract surgery camps', 'All citizens, with priority to senior citizens', 'https://npcbvi.mohfw.gov.in'],
  ['rbsk-sickle', 'Anaemia Mukt Bharat', 'Healthcare', 'Anaemia Control', 'Targeted interventions including iron supplementation, deworming and fortification to reduce anaemia.', 'Free IFA supplements and anaemia screening', 'Children, adolescents, pregnant and lactating women', 'https://anemiamuktbharat.info'],
  ['pm-ab-pmjay-topup', 'Ayushman Bharat – Senior Citizen Top-Up', 'Healthcare', 'Senior Health', 'Extends Ayushman Bharat cover to senior citizens aged 70+ with ₹5 Lakh annual health cover.', '₹5 Lakh health insurance for senior citizens (70+)', 'All senior citizens aged 70 and above', 'https://pmjay.gov.in'],
  ['free-dialysis', 'Pradhan Mantri National Dialysis Programme', 'Healthcare', 'Dialysis', 'Free dialysis services at district and sub-district hospitals for kidney patients.', 'Free dialysis sessions at public facilities', 'All kidney patients requiring dialysis', 'https://nhm.gov.in'],
  ['npcch-hearing', 'Hearing Impairment Screening Programme', 'Healthcare', 'Newborn Screening', 'Universal newborn hearing screening with early rehabilitation support.', 'Free hearing screening and aids for newborns', 'All newborns in public health facilities', 'https://nhm.gov.in'],
  ['tuberculosis-free', 'Pradhan Mantri TB Mukt Bharat 2025', 'Healthcare', 'TB Elimination', 'Community support programme for TB elimination with free diagnostics, treatment and nutrition.', 'Free TB tests, treatment and ₹500/month nutrition support', 'All TB patients and their contacts', 'https://tbcindia.gov.in'],
  ['ayush-gram', 'AYUSH Gram Scheme', 'Healthcare', 'AYUSH Villages', 'Village-level AYUSH wellness programmes integrating traditional medicine in daily life.', 'Free AYUSH camps and wellness services', 'Villages selected for AYUSH interventions', 'https://nam.ayush.gov.in'],
  ['health-helpline', 'National Health Helpline (104)', 'Healthcare', 'Health Helpline', '24x7 tele-health helpline providing medical advice, information and grievance redressal.', 'Free medical advice and teleconsultation round the clock', 'All citizens', 'https://nhm.gov.in'],

  // ── EDUCATION EXTENDED ────────────────────────────────────────────────────
  ['pmsss-ne', 'PM Special Scholarship Scheme for NE (PM Devine)', 'Education', 'NE Scholarships', 'Scholarships for students from North Eastern states for professional and technical courses.', '₹3,500-7,600 per month scholarship support', 'NE region students in professional courses', 'https://pmsne.online-inspire.gov.in'],
  ['nsp-portal', 'National Scholarship Portal (NSP)', 'Education', 'Scholarship Portal', 'Single platform for central and state scholarship application, disbursement and tracking.', 'Online application for all government scholarships', 'All students eligible for government scholarships', 'https://scholarships.gov.in'],
  ['vidyalakshmi-portal', 'Vidya Lakshmi Education Loan Portal', 'Education', 'Education Loans', 'Single window for students to discover, compare and apply for education loans from banks.', 'Loan eligibility check and application on one portal', 'Students seeking education loans', 'https://www.vidyalakshmi.co.in'],
  ['ugc-non-net', 'UGC Non-NET Fellowship', 'Education', 'Research Fellowship', 'Fellowship for PhD scholars in universities without UGC-NET based research support.', '₹8,000-12,000 per month fellowship for PhD', 'PhD scholars in state universities and colleges', 'https://ugc.ac.in'],
  ['scheme-girls-secondary', 'National Scheme of Incentive to Girls for Secondary Education', 'Education', 'Girls Education', 'Incentive for girls from SC/ST families who pass class VIII to continue secondary education.', '₹3,000 one-time incentive deposit for eligible girls', 'Girls from SC/ST families passing class VIII', 'https://scholarships.gov.in'],
  ['nishtha-pratham', 'NISHTHA for Early Childhood', 'Education', 'ECE Training', 'Training of pre-school teachers under National Initiative for School Heads and Teachers Holistic Advancement.', 'Free ECE training and certification for teachers', 'Anganwadi and pre-school teachers', 'https://itpd.ncert.gov.in'],
  ['samagra-digital', 'PM eVIDYA Programme', 'Education', 'Digital Education', 'Multi-mode digital education access including DIKSHA, Swayam Prabha channels, radio and community radio.', 'Free digital education across TV, radio and web', 'All students, especially in remote areas', 'https://pmvdy.education.gov.in'],
  ['navodaya-extension', 'Navodaya Vidyalaya Lateral Entry', 'Education', 'Class IX Admission', 'Lateral entry admission to class IX in Navodaya Vidyalayas for rural students.', 'Free education at class IX level in JNVs', 'Rural students passing class VIII', 'https://navodaya.gov.in'],
  ['gyan-tara', 'Gyan Tara – National Free Online Coaching', 'Education', 'Competitive Coaching', 'Free online coaching for SC/ST students preparing for competitive exams.', 'Free online test series and study material', 'SC/ST students preparing for competitive exams', 'https://www.gyantara.in'],

  // ── WOMEN EXTENDED ────────────────────────────────────────────────────────
  ['mission-shakti-umbrella', 'Mission Shakti – Samarthya & Sakhi', 'Women', 'Women Safety', 'Integrated programme for women safety, rescue and rehabilitation and empowerment services.', 'One Stop Centres, helpline and empowerment services', 'All women, especially those in distress', 'https://wcd.nic.in'],
  ['nanhi-kali', 'Nanhi Kali – Girl Child Education Support', 'Education', 'Girls Education', 'Educational support for underprivileged girl children through material and academic help.', 'Study material, uniforms and remedial classes', 'Girl children from economically weaker families', 'https://www.nanhikali.org'],
  ['sukanya-extension', 'Sukanya Samriddhi – Interest Rates', 'Savings', 'Girl Child Savings', 'Government-backed small savings scheme for girl child education and marriage expenses.', 'High interest (8.2% p.a.) tax-exempt savings account', 'Girls below 10 years of age', 'https://www.nsiindia.gov.in'],
  ['sakhi-niryat', 'Sakhi Niryat – Women Exporters', 'Business', 'Women Exporters', 'Capacity building and mentoring for women entrepreneurs to export their products.', 'Export readiness training and market linkages', 'Women entrepreneurs and SHGs', 'https://niryat.gov.in'],

  // ── PENSIONS & SOCIAL SECURITY EXTENDED ───────────────────────────────────
  ['pension-ladli', 'Ladli Laxmi Yojana (Central Component)', 'Pension', 'Girl Child Savings', 'Savings bonds for girl children maturing at adulthood for educational and marriage needs.', 'Bond of ₹6,000 per year for girl child', 'Girls in BPL families (state variants)', 'https://www.myscheme.gov.in'],
  ['shramik-card', 'Building & Other Construction Workers Welfare', 'Social Security', 'Labour Welfare', 'Cess-funded welfare benefits including health, education and pension for registered construction workers.', 'Health cover, education support and pension for registered workers', 'Registered construction workers under BOCW Act', 'https://bocwwb.gov.in'],
  ['pmjjby-extension', 'PM Jeevan Jyoti Bima Yojana', 'Insurance', 'Life Insurance', 'One-year renewable term life insurance cover for persons in the age group 18-50 years.', '₹2 Lakh life cover at ₹436 per year', 'Bank account holders aged 18-50', 'https://jansuraksha.gov.in'],
  ['pmsby-extension', 'PM Suraksha Bima Yojana', 'Insurance', 'Accident Insurance', 'Accidental death and disability cover for the insured person at a nominal premium.', '₹2 Lakh accidental cover at ₹20 per year', 'Bank account holders aged 18-70', 'https://jansuraksha.gov.in'],
  ['avas-pension', 'National Pension System Lite (Swayalamban)', 'Savings', 'Informal Sector Savings', 'Pension savings with government co-contribution for citizens in the informal sector.', '₹1,000 per year government co-contribution for 10 years', 'Informal sector workers contributing to NPS', 'https://npscra.nsdl.co.in'],
  ['central-family-benefit', 'Central Family Benefit Scheme (CFBS)', 'Social Security', 'Family Support', 'Financial support to families living below the poverty line on death of a breadwinner.', '₹20,000 on death of the primary earner', 'BPL families aged 18-60 losing a breadwinner', 'https://nsap.nic.in'],

  // ── MINORITY & SOCIAL JUSTICE EXTENDED ────────────────────────────────────
  ['minority-business-loan', 'National Minorities Development & Finance Corporation (NMDFC)', 'Business', 'Minority Loans', 'Term loans at concessional interest for minority community members for income generation.', 'Loans up to ₹20 Lakh at 5-8% interest', 'Minority community members below poverty line', 'https://nmdfc.org'],
  ['pm-yasasvi-extension', 'PM YASASVI – Merit Scholarship for OBC/EBC', 'Education', 'OBC Education', 'Scholarship for meritorious OBC, EBC and DNT students from classes IX to XII.', '₹3,000-5,000 per year scholarship with hostel support', 'OBC/EBC/DNT students in classes IX-XII', 'https://yasasvi.ncbc.nic.in'],
  ['sc-livelihood', 'National SC-ST Hub', 'Business', 'SC/ST Entrepreneurship', 'Procurement support for SC/ST entrepreneurs supplying goods and services to government.', 'Market access and entrepreneurship support', 'SC/ST owned MSMEs', 'https://www.scsthub.org'],
  ['van-dhan-extension', 'Van Dhan Vikas Kendra', 'Social Justice', 'Tribal Livelihoods', 'Value addition of minor forest produce by tribal gatherers through cluster-level processing units.', 'Training, processing equipment and marketing support', 'Tribal forest produce gatherers in clusters', 'https://trifed.tribal.gov.in'],
  ['janjati-udyam', 'Janjatiya Udyam Vikas Kendra', 'Social Justice', 'Tribal Entrepreneurship', 'Enterprise development and marketing support for tribal entrepreneurs across sectors.', 'Seed capital and market linkage for tribal enterprises', 'Scheduled Tribe entrepreneurs', 'https://trifed.tribal.gov.in'],

  // ── INFRASTRUCTURE & URBAN EXTENDED ───────────────────────────────────────
  ['pm-dhara', 'PM Dhara – Rural Housing Land Rights', 'Housing', 'Land Rights', 'Provides land rights to eligible rural families to facilitate housing under PMAY-G.', 'Land patta enabling housing construction', 'Landless rural families identified by SECC', 'https://pmayg.nic.in'],
  ['paver-block', 'Swachh Bharat – Individual Household Latrine (IHHL)', 'Housing', 'Sanitation', 'Individual household latrine construction incentive for eligible rural households.', '₹12,000 per household toilet incentive', 'Eligible rural households without toilets', 'https://sbm.gov.in'],
  ['amrut-water', 'AMRUT – Water Connections', 'Urban Development', 'Urban Water Supply', 'Household water tap connections and sewerage services in 500 mission cities.', 'New tap and sewerage connections', 'Urban households in AMRUT cities', 'https://amrut.gov.in'],
  ['pm-street-light', 'Street Light Replacement (DELP)', 'Energy', 'Street Lighting', 'Replacement of conventional street lights with LEDs in urban areas under Energy Efficiency Services.', 'LED street lighting at low cost', 'Urban local bodies', 'https://eeslindia.org'],
  ['jjm-extension', 'Jal Jeevan Mission – Grey Water Management', 'Water', 'Grey Water', 'Greywater management and reuse through soak pits and kitchen garden recharge in villages.', 'Free greywater treatment infrastructure', 'Rural households with tap connections', 'https://ejalshakti.gov.in'],

  // ── EMPLOYMENT & SKILL EXTENDED ───────────────────────────────────────────
  ['nps-kamal', 'Kaushal Aadhaar Card', 'Employment', 'Skill Certification', 'Unique skill ID card for skilled workforce enabling placement and verification.', 'Free skill certification and verification', 'All skilled workers and trainees', 'https://www.skillindia.gov.in'],
  ['national-youth-corps', 'National Youth Corps', 'Employment', 'Youth Service', 'Engages youth in nation-building activities with stipend-based service opportunities.', 'Stipend-based service in community projects', 'Youth aged 18-25 years', 'https://nyks.nic.in'],
  ['pm-vishwakarma-toolkit', 'PM Vishwakarma – Toolkits for Artisans', 'Employment', 'Artisan Support', 'Toolkit incentives and skill upgradation for traditional artisans and craftspeople.', 'Free toolkit worth ₹15,000 and ₹500/day training stipend', 'Artisans from 18 traditional trades', 'https://pmvishwakarma.gov.in'],
  ['ghar-diyare', 'Job Portal – National Career Service (NCS)', 'Employment', 'Job Matching', 'Online job matching platform with career counselling and skill guidance.', 'Free job registration, alerts and counselling', 'All job seekers', 'https://www.ncs.gov.in'],

  // ── FISHERIES / COASTAL / WATER ───────────────────────────────────────────
  ['tsunami-rehab', 'Coastal Zone Livelihood Programme', 'Agriculture', 'Coastal Livelihood', 'Alternative livelihood support for coastal and fishing communities.', 'Alternative income generation support', 'Coastal fishers and vulnerable households', 'https://pmmsy.dof.gov.in'],
  ['aquaculture-extension', 'Fish Farmers Development Agency (FFDA)', 'Agriculture', 'Aquaculture', 'Extension and technical support for freshwater fish farming in ponds and tanks.', 'Pond development subsidy and training', 'Fish farmers and pond owners', 'https://dof.gov.in'],

  // ── TRANSPORT & COMMUNICATION EXTENDED ────────────────────────────────────
  ['metro-ext', 'Metro Rail Connectivity', 'Transport', 'Urban Metro', 'Metro rail connectivity in tier-2 cities for sustainable urban commuting.', 'Affordable metro services', 'Residents of metro cities', 'https://www.metrorailnews.in'],
  ['e-rickshaw', 'E-Rickshaw Promotion Scheme', 'Transport', 'EV Rickshaws', 'Incentives for adoption of electric rickshaws for clean last-mile connectivity.', 'Purchase incentives on e-rickshaws', 'E-rickshaw buyers and drivers', 'https://www.heavyindustries.gov.in'],
  ['digital-village', 'Digital Village / Smart Gram', 'Digital', 'Digital Villages', 'Sets up common service facilities providing digital services in villages.', 'Free access to digital services and e-services', 'Villages covered under the programme', 'https://www.ceg.gov.in'],

  // ── HEALTH & FAMILY WELFARE EXTENDED ──────────────────────────────────────
  ['nvhss', 'National Voluntary Health Services', 'Healthcare', 'Community Health', 'Community-based health volunteers supporting health awareness and service linkage.', 'Free community health services and referral support', 'All households through volunteers', 'https://nhm.gov.in'],
  ['pradhan-mantri-annadata', 'PM Annadata Aay Sanrakshan Abhiyan – Price Deficiency Payment', 'Agriculture', 'Price Support', 'Direct payment of difference between MSP and market price for notified crops.', 'Price deficiency payment on MSP shortfall', 'Farmers registered for notified crops', 'https://pm-aasha.gov.in'],
  ['gramin-bhandaran', 'Gramin Bhandaran Yojana', 'Agriculture', 'Rural Godowns', 'Construction of rural godowns and scientific storage for agricultural produce.', 'Capital subsidy up to 25% on godown construction', 'Farmers, cooperatives and agripreneurs', 'https://agricoop.gov.in'],
  ['dairy-coop-vikas', 'Dairy Cooperative Societies Development', 'Agriculture', 'Dairy Cooperatives', 'Formation and strengthening of dairy cooperative societies in uncovered villages.', 'Grant support for dairy cooperative infrastructure', 'Dairy cooperative societies', 'https://dahd.nic.in'],
  ['organic-northeast', 'Organic Farming Promotion in NE', 'Agriculture', 'Organic NE', 'Promotion of certified organic farming in North Eastern states with market support.', 'Certification cost reimbursement and market linkage', 'Farmers in NE states', 'https://agricoop.gov.in'],
  ['micro-irrigation-fund', 'Micro Irrigation Fund', 'Agriculture', 'Micro Irrigation', 'Provides additional financing for micro-irrigation adoption beyond subsidy ceilings.', 'Cheap financing for drip and sprinkler systems', 'Farmers adopting micro-irrigation', 'https://pmksy.gov.in'],

  // ── SPORTS EXTENDED ───────────────────────────────────────────────────────
  ['khelo-youth', 'Khelo India Youth Games', 'Sports', 'Youth Competitions', 'Annual national multi-sport competition for young athletes with medals and awards.', 'Participation in national games with facilities', 'Young athletes (under 17/21 categories)', 'https://kheloindia.gov.in'],
  ['sports-scholarship', 'Khelo India Scholarship', 'Sports', 'Athlete Support', 'Financial scholarship for identified young sporting talents for coaching and equipment.', '₹1.25 Lakh per year scholarship', 'Athletes identified under Khelo India talent hunt', 'https://kheloindia.gov.in'],
  ['fit-india', 'Fit India Movement', 'Sports', 'Fitness', 'National movement promoting fitness through community exercises, yoga and school fitness programmes.', 'Free fitness activities and resources', 'All citizens', 'https://fitindia.gov.in'],
  ['para-sports', 'Khelo India Para Games', 'Sports', 'Para Athletes', 'Competition and support platform for para athletes with disabilities.', 'Training and competition support for para athletes', 'Athletes with disabilities', 'https://kheloindia.gov.in'],

  // ── CULTURE EXTENDED ──────────────────────────────────────────────────────
  ['sanskriti-scholarship', 'Cultural Talent Search Scholarship', 'Culture', 'Young Artists', 'Scholarships for young persons in the age group 10-14 years in rare art forms.', '₹500-600 per month scholarship for training', 'Young artists in rare and vanishing art forms', 'https://www.indiaculture.gov.in'],
  ['guru-shishya', 'Guru Shishya Parampara Scheme', 'Culture', 'Traditional Arts', 'Supports traditional arts transmission from established gurus to shishyas.', 'Grant support for traditional art training', 'Gurus and disciples of traditional arts', 'https://www.indiaculture.gov.in'],
  ['vocal-for-local', 'Vocal for Local – Handicraft Promotion', 'Business', 'Handicrafts', 'Marketing and design support for handicraft artisans and clusters.', 'Design intervention and market access for artisans', 'Handicraft artisans and clusters', 'https://handicrafts.nic.in'],
  ['pm-megasarthi', 'PM Mega Integrated Textile Region & Apparel (MITRA)', 'Business', 'Textile Parks', 'World-class textile parks with plug-and-play infrastructure for textile manufacturing.', 'Infrastructure and incentives for textile units', 'Textile manufacturers and investors', 'https://pmmittra.gov.in'],

  // ── MISCELLANEOUS CITIZEN SERVICES ────────────────────────────────────────
  ['sugam-bharat', 'Sugamya Bharat Abhiyan', 'Social Justice', 'Accessibility', 'Accessible India campaign making public spaces, transport and websites accessible for persons with disabilities.', 'Accessible public infrastructure and services', 'All persons with disabilities', 'https://accessibleindia.gov.in'],
  ['bharat-net-village', 'BharatNet – GPON Connectivity', 'Digital', 'Rural Broadband', 'Fibre broadband connectivity to all Gram Panchayats for government services and internet.', 'High-speed internet to gram panchayats', 'Rural residents through panchayat networks', 'https://bharatnet.gov.in'],
  ['e-gov-services', 'Common Services Centres (CSC)', 'Digital', 'Digital Services', 'Access points for government e-services in rural areas run by local entrepreneurs.', 'G2C services like certificates, banking and healthcare', 'Rural citizens through CSCs', 'https://www.csc.gov.in'],
  ['national-lottery', 'Swasthya Sanjeevani – Health Insurance for NE', 'Healthcare', 'NE Health', 'Health insurance coverage for families in North Eastern states.', '₹5 Lakh health insurance cover', 'Residents of North Eastern states', 'https://pmjay.gov.in']
];
