/**
 * Additional Central Government Welfare Schemes Dataset
 * [external_id, title, category, tag, description, benefit, eligibility, source_url]
 * Seeded via stateSchemesAdapter under source 'stateSchemes'.
 */
export const CENTRAL_SCHEMES = [
  // ── AGRICULTURE & FARMER SUPPORT ──────────────────────────────────────────
  ['nmsa', 'National Mission for Sustainable Agriculture (NMSA)', 'Agriculture', 'Soil & Water', 'Promotes sustainable agriculture through soil health management, rainfed area development, and water-efficient farming practices.', 'Financial support for soil amendments, micro-irrigation and climate-resilient crops', 'All farmers willing to adopt sustainable agricultural practices', 'https://nmsa.dac.gov.in'],
  ['midh', 'Mission for Integrated Development of Horticulture (MIDH)', 'Agriculture', 'Horticulture', 'Holistic development of horticulture sector covering fruits, vegetables, spices, flowers, and medicinal plants with end-to-end supply chain support.', 'Subsidy up to 50% on horticulture plantation, protected cultivation and cold chain', 'Horticulture farmers, growers, and producer groups', 'https://midh.gov.in'],
  ['nfsm', 'National Food Security Mission (NFSM)', 'Agriculture', 'Foodgrain Production', 'Augments production of rice, wheat, pulses, coarse cereals, and oilseeds through area expansion and productivity enhancement.', 'Subsidised certified seeds, fertilizers and farm machinery at notified rates', 'Crop-growing farmers in identified districts', 'https://nfsm.gov.in'],
  ['rkvy-raftaar', 'Rashtriya Krishi Vikas Yojana (RKVY-RAFTAAR)', 'Agriculture', 'State Agri Development', 'Remunerative Approaches for Agriculture and Allied Sector Rejuvenation, funding state-level agricultural development projects.', 'Grants for state agricultural plans, value chains and agri-innovation', 'State governments, FPOs and agri-entrepreneurs', 'https://rkvy.nic.in'],
  ['pm-dhan-dhanya', 'PM Dhan Dhanya Krishi Yojana', 'Agriculture', 'Farmer Prosperity', 'Comprehensive scheme to boost agricultural productivity, reduce input costs, and improve farmer incomes in identified districts across India.', 'Aggregated support: irrigation, quality seeds, credit, and crop diversification assistance', 'Farmers in notified high-potential agricultural districts', 'https://agricoop.gov.in'],
  ['pm-aasha', 'PM Annadata Aay Sanrakshan Abhiyan (PM-AASHA)', 'Agriculture', 'Price Support', 'Ensures remunerative prices to farmers through Minimum Support Price (MSP) procurement and Price Deficiency Payment mechanisms.', 'Assured MSP for notified oilseeds, pulses and copra crops', 'Farmers selling notified crops in designated mandis', 'https://pm-aasha.gov.in'],
  ['e-nam', 'National Agriculture Market (e-NAM)', 'Agriculture', 'Market Linkage', 'Pan-India electronic trading portal that networks APMC mandis for transparent price discovery of agricultural produce.', 'Online platform to sell produce across states with better price realisation', 'Farmers registered with their APMC or mandi', 'https://enam.gov.in'],
  ['national-bee-mission', 'National Bee Mission', 'Agriculture', 'Apiculture', 'Promotes scientific beekeeping to boost crop pollination, honey production and farmer income through cluster-based apiaries.', '50% subsidy on beehives, equipment and training for beekeepers', 'Farmers, rural youth and beekeeping enterprises', 'https://nbb.gov.in'],
  ['fpo-scheme', 'Formation & Promotion of 10,000 FPOs', 'Agriculture', 'Farmer Producer Organisations', 'Promotes formation and capacity building of Farmer Producer Organisations to aggregate produce and improve farmer bargaining power.', 'Financial support up to ₹15 Lakh per FPO over 5 years for professional management', 'Farmers willing to form FPOs through cluster-based approach', 'https://fpo.gov.in'],
  ['krishi-udan', 'Krishi UDAN Scheme', 'Agriculture', 'Air Cargo Logistics', 'Facilitates seamless air transportation of perishable agri-produce from surplus regions to national and international markets.', 'Air cargo freight concessions and cold-chain support for farm produce', 'Farmers, FPOs, and agri-exporters', 'https://krishiudan.gov.in'],
  ['crop-residue-management', 'Crop Residue Management Scheme', 'Agriculture', 'Stubble Burning Control', 'Provides machinery support to prevent stubble burning and manage crop residue through in-situ and ex-situ methods.', 'Subsidy up to 50% on super seeder, happy seeder and balers', 'Farmers in rice-wheat cropping system states', 'https://crm.agricoop.nic.in'],
  ['nicra', 'National Initiative on Climate Resilient Agriculture (NICRA)', 'Agriculture', 'Climate Adaptation', 'Demonstrates climate-resilient crop varieties, water-saving technologies and adaptation practices in vulnerable villages.', 'Free technical support, resilient seeds and climate-proofing demonstration', 'Farmers in climate-vulnerable districts', 'https://nicra.icar.in'],
  ['nmeo-oilseeds', 'National Mission on Edible Oils – Oilseeds (NMEO-Oilseeds)', 'Agriculture', 'Oilseeds', 'Enhances domestic oilseed production through seed distribution, crop diversification and procurement support.', 'Subsidy on quality oilseed seeds and price support on procurement', 'Oilseed growers in notified districts', 'https://nmoop.gov.in'],
  ['nmeo-oilpalm', 'National Mission on Edible Oils – Oil Palm (NMEO-Oil Palm)', 'Agriculture', 'Oil Palm', 'Expands oil palm cultivation with financial assistance for planting material, irrigation, and area expansion.', '₹26,000 to ₹29,000 per hectare assistance over 4 years for oil palm growers', 'Farmers in suitable agro-climatic zones with assured irrigation', 'https://nmeo-op.gov.in'],
  ['watershed-development', 'Watershed Development Component (PMKSY-WDC)', 'Agriculture', 'Soil & Water Conservation', 'Develops wastelands and degraded watersheds through soil conservation, rainwater harvesting and livelihood support.', 'Free watershed development works on participating community lands', 'Villagers in notified watershed development projects', 'https://pmksy.gov.in'],
  ['agri-credit-subvention', 'Agriculture Credit Interest Subvention Scheme', 'Agriculture', 'Farm Credit', 'Provides short-term crop loans at concessional interest rates to farmers through institutional credit channels.', 'Crop loans at 4% interest after subvention (up to ₹3 Lakh)', 'Farmers with Kisan Credit Cards and short-term crop loans', 'https://nabard.org'],
  ['sub-mission-seeds', 'Sub-Mission on Seeds and Planting Material', 'Agriculture', 'Quality Seeds', 'Strengthens seed production chain from breeder to certified seed and provides quality seed at subsidised rates.', 'Subsidised certified seeds up to 50% cost for farmers', 'All registered farmers', 'https://agricoop.gov.in'],
  ['atma', 'Agricultural Technology Management Agency (ATMA)', 'Agriculture', 'Extension Services', 'Disseminates modern farming technologies, farmer training and demonstration through district-level extension network.', 'Free farmer training, demonstrations and exposure visits', 'All farmers through district ATMA cells', 'https://atma.gov.in'],

  // ── ANIMAL HUSBANDRY, DAIRY & FISHERIES ───────────────────────────────────
  ['lhdcp', 'Livestock Health & Disease Control Programme', 'Agriculture', 'Animal Health', 'Vaccination and disease control for major livestock diseases to protect farmer livelihoods.', 'Free vaccination and veterinary camps for livestock', 'All livestock owners', 'https://dahd.nic.in'],
  ['ahidf', 'Animal Husbandry Infrastructure Development Fund', 'Agriculture', 'Dairy Infrastructure', 'Provides loan support for setting up dairy processing, meat processing, and animal feed infrastructure.', '3% interest subvention on loans up to ₹25 Crores for eligible projects', 'Dairy cooperatives, FPOs, MSMEs and private entrepreneurs', 'https://ahidf.udyamimitra.in'],
  ['npdd', 'National Programme for Dairy Development', 'Agriculture', 'Dairy Development', 'Strengthens dairy cooperatives and producer companies, improving milk procurement and processing capacity.', 'Financial assistance for dairy infrastructure and cooperative capacity building', 'Milk unions, federations and dairy farmers', 'https://dahd.nic.in'],
  ['deds', 'Dairy Entrepreneurship Development Scheme (DEDS)', 'Agriculture', 'Dairy Entrepreneurship', 'Promotes small dairy enterprises including milk production, processing and cattle feed manufacturing.', 'Capital subsidy up to 25% (max ₹30 Lakh) on dairy projects', 'Farmers, youth and entrepreneurs with bankable dairy projects', 'https://dahd.nic.in'],
  ['fidf', 'Fisheries & Aquaculture Infrastructure Development Fund', 'Agriculture', 'Fisheries Infrastructure', 'Provides affordable credit for development of fishing harbours, cold chains and aquaculture infrastructure.', '2% interest subvention on loans up to ₹100 Crore', 'State governments, cooperatives and fisheries enterprises', 'https://fidf.gov.in'],
  ['blue-revolution', 'Blue Revolution – Integrated Development of Fisheries', 'Agriculture', 'Fisheries', 'Framework for holistic fisheries development including inland and marine fisheries, aquaculture and fish processing.', 'Subsidy support for pond construction, hatcheries and fish seed', 'Fish farmers, fishers and fishery cooperatives', 'https://dof.gov.in'],

  // ── ENERGY & ENVIRONMENT ──────────────────────────────────────────────────
  ['ujala-led', 'UJALA – LED Distribution Scheme', 'Energy', 'Energy Efficiency', 'Replaces inefficient incandescent bulbs with energy-efficient LED bulbs at subsidised rates through DISCOM outlets.', 'LED bulbs at ₹80-110 per bulb with buy-back of old bulbs', 'All domestic electricity consumers', 'https://ujala.gov.in'],
  ['saubhagya', 'Pradhan Mantri Sahaj Bijli Har Ghar Yojana (Saubhagya)', 'Energy', 'Electrification', 'Last-mile electrification providing free electricity connections to un-electrified households across India.', 'Free electricity connection with metering to every household', 'All un-electrified rural and urban households', 'https://saubhagya.gov.in'],
  ['national-bioenergy', 'National Bioenergy Programme', 'Energy', 'Bioenergy', 'Supports waste-to-energy, biomass cogeneration, and biogas generation for clean power and better waste management.', 'Capital subsidy and viability gap funding for bioenergy plants', 'Entrepreneurs, local bodies and farmers with agro-waste', 'https://mnre.gov.in'],
  ['nbmmp', 'National Biogas & Manure Management Programme', 'Energy', 'Biogas', 'Sets up family-size biogas plants converting cattle dung into cooking fuel and enriched manure.', 'Subsidy on small biogas plants for rural households', 'Rural households owning cattle', 'https://mnre.gov.in'],
  ['green-energy-corridor', 'Green Energy Corridor', 'Energy', 'Renewable Grid', 'Evacuates renewable energy through dedicated transmission corridors connecting solar and wind parks.', 'Reliable grid access for renewable energy producers', 'Renewable energy generators and project developers', 'https://mnre.gov.in'],
  ['solar-charkha', 'Solar Charkha Mission', 'Energy', 'Solar Livelihood', 'Runs solar-powered charkha clusters providing green employment and khadi production in rural areas.', 'Solar charkha units, working capital and market linkage for artisans', 'Rural artisans and women self-help groups', 'https://mowcd.gov.in'],
  ['mishti', 'Mangrove Initiative for Shoreline Habitats (MISHTI)', 'Environment', 'Mangrove Restoration', 'Restores and promotes mangrove cover along India’s coastline and saltpan lands for ecological resilience.', 'Free mangrove plantation and community conservation support', 'Coastal communities and local bodies', 'https://moef.gov.in'],
  ['amrit-dharohar', 'Amrit Dharohar – Wetland Conservation', 'Environment', 'Wetlands', 'Enhances conservation of Ramsar wetlands while promoting sustainable livelihood opportunities for local communities.', 'Wetland restoration and eco-tourism livelihood support', 'Communities around notified wetlands', 'https://wetlandsindia.com'],
  ['green-india-mission', 'National Green India Mission', 'Environment', 'Afforestation', 'Enhances forest cover and ecosystem services through afforestation on degraded lands and village commons.', 'Free saplings, plantation drives and employment generation', 'Forest fringe villagers and local communities', 'https://moef.gov.in'],
  ['jal-shakti-abhiyan', 'Jal Shakti Abhiyan', 'Environment', 'Water Conservation', 'Catch the Rain campaign focusing on rainwater harvesting, water recharge and watershed management across districts.', 'Free technical support for rainwater harvesting structures', 'All rural and urban communities', 'https://jalshaktikendra.gov.in'],

  // ── HEALTHCARE & NUTRITION ────────────────────────────────────────────────
  ['intensified-mission-indradhanush', 'Intensified Mission Indradhanush', 'Healthcare', 'Immunization', 'Special drives to reach children and pregnant women missed by routine immunisation with all life-saving vaccines.', 'Free vaccination for all missed children (0-2 years) and pregnant women', 'Children and pregnant women not fully immunised', 'https://nhm.gov.in'],
  ['rbsk', 'Rashtriya Bal Swasthya Karyakram (RBSK)', 'Healthcare', 'Child Health Screening', 'Health screening of children for 30 health conditions including defects at birth, deficiencies, diseases and developmental delays.', 'Free screening and early treatment referrals for school-age children', 'Children aged 0-18 years, especially school-going', 'https://nhm.gov.in'],
  ['jsy', 'Janani Suraksha Yojana (JSY)', 'Healthcare', 'Safe Delivery', 'Cash incentive to pregnant women for institutional delivery to reduce maternal and infant mortality.', '₹1,400 (rural) / ₹1,000 (urban) cash benefit for institutional delivery', 'BPL pregnant women above 19 years delivering in health institutions', 'https://nhm.gov.in'],
  ['jssk', 'Janani Shishu Suraksha Karyakram (JSSK)', 'Healthcare', 'Free Maternal Care', 'Entitlement of free and cashless delivery care, including free drugs, diagnostics, diet and transport for pregnant women and sick newborns.', 'Fully free delivery, medicines, diagnostics and referral transport', 'All pregnant women delivering in public health facilities', 'https://nhm.gov.in'],
  ['rksk', 'Rashtriya Kishor Swasthya Karyakram (RKSK)', 'Healthcare', 'Adolescent Health', 'Addresses health needs of adolescents including nutrition, sexual health, substance misuse and mental health.', 'Weekly Iron-Folic Acid, deworming and adolescent-friendly clinics', 'Adolescents in the age group 10-19 years', 'https://nhm.gov.in'],
  ['ayushman-arogya-mandir', 'Ayushman Arogya Mandir', 'Healthcare', 'Primary Health', 'Transforms SHC/PHC into comprehensive primary healthcare centres delivering wellness, prevention and treatment.', 'Free primary care, diagnostics, medicines and tele-consultation', 'All citizens through their nearest wellness centre', 'https://ab-hwc.nhp.gov.in'],
  ['rashtriya-arogya-nidhi', 'Rashtriya Arogya Nidhi (RAN)', 'Healthcare', 'Treatment Assistance', 'Provides financial assistance to poor patients for treatment of life-threatening diseases in government hospitals.', 'Up to ₹5 Lakh financial assistance for eligible surgeries and treatments', 'BPL patients treated in government hospitals for notified diseases', 'https://mohfw.gov.in'],
  ['sickle-cell-mission', 'National Sickle Cell Anaemia Elimination Mission', 'Healthcare', 'Tribal Health', 'Screening, counselling and treatment for sickle cell anaemia with a focus on tribal populations.', 'Free screening, counselling and treatment at district level', 'All persons screened positive, especially in tribal belts', 'https://sicklecellmission.gov.in'],
  ['national-ayush-mission', 'National Ayush Mission', 'Healthcare', 'AYUSH Services', 'Strengthens AYUSH healthcare delivery including Ayurveda, Yoga, Naturopathy, Unani, Siddha and Homeopathy services.', 'Free medicines and treatment at government AYUSH facilities', 'All citizens', 'https://nam.ayush.gov.in'],
  ['pmsma', 'Pradhan Mantri Surakshit Matritva Abhiyan (PMSMA)', 'Healthcare', 'Antenatal Care', 'Fixed-day assured antenatal check-ups for pregnant women by specialist doctors in government facilities.', 'Free comprehensive ANC check-up on 9th of every month', 'All pregnant women in second and third trimester', 'https://pmsma.nhp.gov.in'],
  ['npcdcs', 'National Programme for Prevention & Control of Non-Communicable Diseases (NP-NCD)', 'Healthcare', 'NCD Screening', 'Screening and treatment for hypertension, diabetes, and common cancers at the primary care level.', 'Free screening and medicines at NCD clinics', 'All citizens above 30 years at risk of NCDs', 'https://ncdindia.org'],
  ['nphce', 'National Programme for Health Care of the Elderly (NPHCE)', 'Healthcare', 'Elderly Health', 'Specialised geriatric health care through district geriatric clinics and mobile units for elderly citizens.', 'Free geriatric OPD services, medicines and home-based care', 'All senior citizens (60+)', 'https://mohfw.gov.in'],
  ['ntcp', 'National Tobacco Control Programme', 'Healthcare', 'Tobacco Cessation', 'Implements tobacco control measures, cessation clinics and IEC campaigns against tobacco use.', 'Free counselling and de-addiction support at tobacco clinics', 'All citizens, especially tobacco users', 'https://ntcp.nhp.gov.in'],
  ['nrc', 'Nutrition Rehabilitation Centres', 'Healthcare', 'Malnutrition Treatment', 'Facility-based management of severely acute malnourished (SAM) children with therapeutic feeding.', 'Free 14-day therapeutic feeding and treatment for SAM children', 'Children under 5 identified as severely undernourished', 'https://nhm.gov.in'],
  ['cghs', 'Central Government Health Scheme (CGHS)', 'Healthcare', 'Employee Health', 'Comprehensive healthcare for central government employees, pensioners and their dependants.', 'Cashless treatment, medicines and diagnostic facilities at empanelled centres', 'Central government employees and pensioners', 'https://cghs.gov.in'],

  // ── EDUCATION & SCHOLARSHIPS ──────────────────────────────────────────────
  ['rte-act', 'Right to Education (RTE) – Free & Compulsory Education', 'Education', 'School Education', 'Guarantees free and compulsory elementary education to children aged 6-14 years.', 'Free admission and education in neighbourhood schools', 'All children aged 6-14 years', 'https://rte.gov.in'],
  ['kgbv', 'Kasturba Gandhi Balika Vidyalaya (KGBV)', 'Education', 'Girls Residential School', 'Residential schools for girls from SC, ST, OBC and minority communities in educationally backward blocks.', 'Free residential education for girls at upper primary level', 'Girls from SC/ST/OBC/minority families in educationally backward blocks', 'https://samagra.education.gov.in'],
  ['emrs', 'Eklavya Model Residential School', 'Education', 'Tribal Education', 'Residential schools providing quality education to tribal students in every tribal sub-plan block.', 'Free residential education with scholarships from class VI to XII', 'Scheduled Tribe students', 'https://emrs.tribal.gov.in'],
  ['navodaya', 'Jawahar Navodaya Vidyalaya (JNV)', 'Education', 'Residential School', 'Nationwide residential schools offering free quality education from class VI to XII with lateral entry.', 'Free education, boarding and lodging at Navodaya Vidyalayas', 'Students selected through JNVST from rural areas (class V)', 'https://navodaya.gov.in'],
  ['pmsss-jk', 'PM Special Scholarship Scheme for J&K (PMSSS)', 'Education', 'Higher Education J&K', 'Scholarship for students from Jammu & Kashmir to pursue professional and degree courses outside the UT.', 'Tuition fee, maintenance and course fee support', 'Students from J&K admitted in recognised institutions outside the UT', 'https://www.jkap.nic.in'],
  ['national-overseas-scholarship', 'National Overseas Scholarship (NOS)', 'Education', 'Overseas Studies', 'Supports meritorious students from SC, ST and landless labourer families for masters and PhD abroad.', 'Full tuition, living allowance and airfare for studies abroad', 'SC/ST/landless labourer students with first-class degrees', 'https://nosmsje.gov.in'],
  ['ishan-uday', 'Ishan Uday – UGC Scholarship for North East', 'Education', 'NE Students', 'Special UGC scholarship to encourage students from North East region to pursue higher education.', '₹5,400 per month scholarship for 20,000 NE students', 'NE region students pursuing general degree courses', 'https://ugc.ac.in'],
  ['swayam', 'SWAYAM – Online Learning Platform', 'Education', 'Online Education', 'Free massive open online courses from class IX to post-graduation with transferable credits.', 'Free certified online courses from top institutions', 'All students and lifelong learners', 'https://swayam.gov.in'],
  ['diksha', 'DIKSHA – Digital Learning Platform', 'Education', 'Digital Content', 'National digital platform hosting teacher resources and learning material for all grades.', 'Free digital textbooks, videos and interactive lessons', 'All students and teachers', 'https://diksha.gov.in'],
  ['nios', 'National Institute of Open Schooling (NIOS)', 'Education', 'Open Schooling', 'Open and distance learning from secondary to senior secondary and vocational courses.', 'Flexible open school education with vocational training', 'Dropouts and learners who cannot attend regular school', 'https://nios.ac.in'],
  ['indira-gandhi-pg', 'Indira Gandhi PG Scholarship for Single Girl Child', 'Education', 'Girl Child Higher Ed', 'UGC scholarship supporting a single girl child in her family for postgraduate studies.', '₹36,200 per year for PG studies (1,000 awards)', 'Single girl child (only child) pursuing PG studies', 'https://ugc.ac.in'],
  ['manf', 'Maulana Azad National Fellowship (MANF)', 'Education', 'Minority Research', 'Five-year fellowship for minority community students pursuing MPhil and PhD.', 'Fellowship of ₹25,000-28,000 per month plus contingencies', 'Minority students with MPhil/PhD admission', 'https://manf.ugc.ac.in'],
  ['pradhan-mantri-usha', 'PM Uchchatar Shiksha Abhiyan (PM-USHA)', 'Education', 'Higher Education', 'State higher education system development including new colleges, research support and digital infrastructure.', 'Grants for state higher education institutions', 'State universities and colleges under the mission', 'https://pmusha.gov.in'],
  ['saksham', 'AICTE Saksham Scholarship', 'Education', 'Girls Technical Education', 'Scholarship for differently-abled students and girls pursuing technical diploma education.', '₹50,000 per year for diploma students', 'Girls and differently-abled students in AICTE diploma programmes', 'https://www.aicte-india.org'],
  ['vigyan-jyoti', 'Vigyan Jyoti – Science for Girls', 'Education', 'Girls in STEM', 'Merit-based scheme encouraging girl students in classes IX-XII to pursue STEM careers.', 'Guidance, mentoring, and exposure for meritorious girl students', 'Girl students from class IX selected through district screening', 'https://vigyanjyoti.gov.in'],
  ['national-digital-library', 'National Digital Library of India (NDLI)', 'Education', 'Digital Library', 'Single-window access to millions of academic resources across disciplines and languages.', 'Free access to books, journals, videos and question banks', 'All students, teachers and researchers', 'https://ndl.iitkgp.ac.in'],
  ['kvs-admission', 'Kendriya Vidyalaya Sangathan Admission', 'Education', 'Central Schools', 'Admission to central government schools providing quality education with facilities, for eligible children.', 'Quality school education in central schools', 'Children of central govt employees and general category with vacancies', 'https://kvsangathan.nic.in'],
  ['nishtha', 'NISHTHA Teacher Training', 'Education', 'Teacher Training', 'National initiative for teacher training through integrated training modules for school teachers.', 'Free competency-based training for teachers', 'Teachers of government and aided schools', 'https://itpd.ncert.gov.in'],
  ['naya-manzil', 'Naya Manzil – Integrated Education & Skill', 'Education', 'Minority Skill', 'Bridge course combining formal education and vocational skills for minority community dropouts.', 'Free schooling equivalence plus vocational training with stipend', 'Minority youth (17-35 years) who are school dropouts', 'https://nayamanzil.minorityaffairs.gov.in'],
  ['nai-udaan', 'Nai Udaan – Support for Minority Students', 'Education', 'Minority Education', 'Financial support for minority students clearing prelims of competitive examinations like UPSC/State PSC.', 'One-time ₹1 Lakh support for selected candidates', 'Minority community candidates clearing competitive exam prelims', 'https://naiudaan.minorityaffairs.gov.in'],

  // ── SKILL DEVELOPMENT & EMPLOYMENT ────────────────────────────────────────
  ['sankalp', 'Skills Acquisition & Knowledge Awareness for Livelihood (SANKALP)', 'Employment', 'Skill Ecosystem', 'World Bank-assisted programme strengthening the short-term skill training ecosystem across districts.', 'Certified short-term skill training at low or no cost', 'Youth aged 15-45, with focus on disadvantaged groups', 'https://msde.gov.in'],
  ['rseti', 'Rural Self Employment Training Institutes (RSETI)', 'Employment', 'Rural Entrepreneurship', 'Free residential skill training to unemployed rural youth for self-employment ventures.', 'Free training, loans and mentoring for rural enterprises', 'Unemployed rural youth aged 18-45', 'https://rseti.gov.in'],
  ['pmrpy', 'Pradhan Mantri Rojgar Protsahan Yojana (PMRPY)', 'Employment', 'Employer EPF Support', 'Government pays the full EPF contribution of eligible employees to incentivise formal job creation.', 'Employer EPF contribution (12%) paid by government for 3 years', 'New employees earning up to ₹15,000/month in registered firms', 'https://pmrpy.gov.in'],
  ['seekho-aur-kamao', 'Seekho aur Kamao – Minority Skill Scheme', 'Employment', 'Minority Skilling', 'Skill development for minority community youth aligned with current industry requirements.', 'Free vocational training with monthly stipend during training', 'Minority community youth aged 14-35 years', 'https://seekhoaurkamao.gov.in'],
  ['pmgdisha', 'Pradhan Mantri Gramin Digital Saksharta Abhiyan (PMGDISHA)', 'Employment', 'Digital Literacy', 'Makes six crore rural citizens digitally literate covering basics of computers, internet and digital payments.', 'Free digital literacy training to rural households', 'Rural citizens aged 14-60 years in non-smartphone literate families', 'https://pmgdisha.gov.in'],
  ['strive', 'STRIVE – Skill Training Improvement', 'Employment', 'ITI Modernisation', 'Improves the quality and market relevance of ITI training through institutional reforms and industry linkage.', 'Modernised ITI training and industry-linked placement support', 'ITI students and trainees across India', 'https://strive.gov.in'],
  ['jan-sikshan-sansthan', 'Jan Shikshan Sansthan (JSS)', 'Employment', 'Vocational for Neo-literates', 'Skill training for neo-literates, rural youth and women in traditional and modern vocations.', 'Free vocational courses with certification', 'Neo-literates, school dropouts and women', 'https://jss.gov.in'],

  // ── WOMEN, CHILD & FAMILY WELFARE ─────────────────────────────────────────
  ['mahila-shakti-kendra', 'Pradhan Mantri Mahila Shakti Kendra', 'Women', 'Women Empowerment', 'Community-level facilitation centres providing convergence of services and empowerment for women.', 'Information, grievance help and skill linkage at block level', 'All women through block-level centres', 'https://wcd.nic.in'],
  ['swadhar-greh', 'Swadhar Greh – Shelter for Women', 'Women', 'Women in Distress', 'Emergency shelter, food, clothing and counselling for women in difficult circumstances.', 'Free shelter and rehabilitation support for women', 'Women in distress without any support system', 'https://wcd.nic.in'],
  ['ujjawala-anti-trafficking', 'Ujjawala – Anti Human Trafficking Scheme', 'Women', 'Anti-Trafficking', 'Prevention, rescue, rehabilitation, reintegration and repatriation of victims of trafficking for commercial sexual exploitation.', 'Rescue, shelter, counselling and livelihood for trafficking victims', 'Women and children victims or at risk of trafficking', 'https://wcd.nic.in'],
  ['samarthya', 'Samarthya – Scheme for Women in Difficult Circumstances', 'Women', 'Women Rehabilitation', 'Convergent rehabilitation for women facing violence, homelessness or distress including short-stay homes.', 'Shelter, vocational training and legal aid for women', 'Women in distress needing temporary shelter and support', 'https://wcd.nic.in'],
  ['mahila-e-haat', 'Mahila E-Haat', 'Women', 'Women Entrepreneurship', 'Online marketing platform for women entrepreneurs and SHGs to sell their products directly.', 'Free online marketplace for women entrepreneurs', 'Women entrepreneurs, SHGs and individual women sellers', 'https://mahilaehaat-rmk.gov.in'],
  ['saras-aajeevika-mela', 'Saras Aajeevika Mela', 'Women', 'SHG Marketing', 'Platforms for rural women SHGs to display and sell their products in major cities.', 'Market linkage and exhibition space for SHG products', 'Rural women self-help groups', 'https://nrlm.gov.in'],
  ['palna-existing', 'Palna – National Creche Scheme', 'Child Welfare', 'Day Care', 'Day-care facilities for children (6 months to 6 years) of working mothers under Mission Shakti.', 'Free or subsidised creche, nutrition and preschool education', 'Working mothers with children aged 6 months-6 years', 'https://wcd.nic.in'],
  ['kishori', 'Kishori Shakti Yojana', 'Child Welfare', 'Adolescent Girls', 'Empowerment of adolescent girls with nutrition, life skills, and vocational training under ICDS.', 'Nutrition, education and life-skill support for girls 11-18', 'Adolescent girls in 11-18 age group in selected areas', 'https://icds-wcd.nic.in'],

  // ── SOCIAL SECURITY, PENSIONS & INSURANCE ─────────────────────────────────
  ['igndps-pension', 'Indira Gandhi National Disability Pension Scheme', 'Pension', 'Disability Pension', 'Monthly pension for persons with severe or multiple disabilities living below the poverty line.', '₹300 per month (with state top-ups)', 'Persons aged 18-79 years with 80%+ disability in BPL families', 'https://nsap.nic.in'],
  ['annapurna-scheme', 'Annapurna Yojana', 'Food Security', 'Elderly Food Security', 'Provides 10 kg of free foodgrains per month to eligible senior citizens not covered under NFSA.', '10 kg free foodgrains every month', 'Senior citizens aged 60+ without any other support', 'https://nsap.nic.in'],
  ['nfbs', 'National Family Benefit Scheme (NFBS)', 'Social Security', 'Bereavement Support', 'Lump sum financial assistance to families on the death of the primary breadwinner.', '₹20,000 one-time assistance to the bereaved family', 'BPL families on death of earning member aged 18-60', 'https://nsap.nic.in'],
  ['nps-vatsalya', 'NPS Vatsalya – Child Pension Account', 'Savings', 'Child Savings', 'National Pension System account for minors, giving children a retirement corpus from an early age.', 'Pension savings account with NPS returns for children', 'Children below 18 years with guardian', 'https://vatsalya.npscra.nsdl.co.in'],
  ['nps-citizens', 'National Pension System (NPS) for All Citizens', 'Savings', 'Retirement Savings', 'Voluntary pension savings with tax benefits and annuity options for all Indian citizens.', 'Market-linked pension savings with tax benefits', 'All citizens aged 18-65 (excluding those in mandatory NPS)', 'https://www.npscra.nsdl.co.in'],

  // ── SC/ST/OBC & MINORITY WELFARE ──────────────────────────────────────────
  ['shreshta', 'SHRESHTA – Residential Education for SC Students', 'Social Justice', 'SC Education', 'Residential education in private residential schools for meritorious SC students in class IX-XII.', 'Full tuition, boarding and lodging for SC students in top schools', 'SC students in classes IX and XI selected through national test', 'https://shreshta.ncsc.nic.in'],
  ['nfo-obc', 'National Fellowship for OBC Students', 'Education', 'OBC Research', 'Fellowship for OBC students pursuing MPhil and PhD courses.', '₹25,000-28,000 per month fellowship for research studies', 'OBC students with MPhil/PhD admission', 'https://nfo.ncbc.nic.in'],
  ['nos-sc', 'National Overseas Scholarship for SC Students', 'Education', 'SC Overseas', 'Financial support for SC students pursuing higher studies abroad.', 'Tuition, living expenses and airfare for master/PhD abroad', 'SC students with first-class degrees seeking overseas admission', 'https://nosmsje.gov.in'],
  ['padho-pardesh-existing', 'Padho Pardesh – Interest Subsidy for Minority Overseas Studies', 'Education', 'Minority Overseas', 'Interest subsidy on education loans taken by minority students for overseas studies.', '100% interest subsidy on overseas education loans', 'Minority students pursuing professional courses abroad', 'https://minorityaffairs.gov.in'],
  ['hamari-darohar', 'Hamari Darohar – Minority Heritage Scheme', 'Social Justice', 'Minority Culture', 'Preserves rich heritage of minority communities by conserving their important sites and artefacts.', 'Grants for conservation of minority heritage sites', 'Organisations and institutions preserving minority heritage', 'https://minorityaffairs.gov.in'],
  ['multi-sectoral-minority', 'Multi-Sectoral Development Programme (MSDP)', 'Social Justice', 'Minority Area Development', 'Infrastructure and livelihood development in minority-concentration districts.', 'Schools, skill centres, hostels and infrastructure in notified blocks', 'Minority concentration areas and communities', 'https://minorityaffairs.gov.in'],
  ['st-hosts', 'Post-Matric Hostel for ST Students', 'Education', 'ST Hostels', 'Hostel facilities enabling ST students to pursue higher and technical education away from home.', 'Free hostel accommodation and maintenance grant', 'Scheduled Tribe students in post-matric courses', 'https://tribal.nic.in'],
  ['pre-matric-st', 'Pre-Matric Scholarship for ST Students', 'Education', 'ST Education', 'Scholarship to reduce dropout rates of ST students in classes IX and X.', '₹350-650 per month scholarship with annual allowance', 'ST students in classes IX-X whose parents are in manual occupations', 'https://tribal.nic.in'],
  ['ncs-scholarship', 'National Coaching Scheme (NCS)', 'Education', 'Coaching Support', 'Coaching for SC/ST/OBC and minority students to prepare for competitive examinations.', 'Free coaching with stipend for competitive exam preparation', 'SC/ST/OBC/minority students preparing for competitive exams', 'https://ncsc.nic.in'],

  // ── RURAL & URBAN DEVELOPMENT ─────────────────────────────────────────────
  ['rurban-mission', 'Shyama Prasad Mukherji RURBAN Mission', 'Rural Development', 'Rurban Clusters', 'Develops growth clusters bridging rural-urban divide with basic and economic infrastructure.', 'Cluster infrastructure, skill and economic development', 'Villages identified in rurban clusters', 'https://rurban.gov.in'],
  ['smart-cities', 'Smart Cities Mission', 'Urban Development', 'Smart Cities', 'Develops 100 cities with core infrastructure and smart solutions for quality urban living.', 'Smart urban infrastructure and digital citizen services', 'Residents of notified smart cities', 'https://smartcities.gov.in'],
  ['amrut-2', 'Atal Mission for Rejuvenation & Urban Transformation 2.0', 'Urban Development', 'Urban Water', 'Universal water supply and septage management in all statutory towns.', 'Tap connections, water treatment and sewage infrastructure', 'All urban households in mission towns', 'https://amrut.gov.in'],
  ['sbm-u-2', 'Swachh Bharat Mission Urban 2.0', 'Urban Development', 'Urban Sanitation', 'Garbage-free and wastewater-free cities through solid waste processing and sanitation infrastructure.', 'Waste collection, processing and legacy dump remediation', 'All urban local bodies', 'https://sbmurban.org'],
  ['amrit-sarovar', 'Mission Amrit Sarovar', 'Rural Development', 'Water Bodies', 'Develops and rejuvenates 75,000 ponds across India for water conservation in every district.', 'Pond rejuvenation and water storage infrastructure', 'Villages with identified ponds for development', 'https://amritsarovar.gov.in'],
  ['sagy', 'Saansad Adarsh Gram Yojana (SAGY)', 'Rural Development', 'Model Village', 'Members of Parliament adopt villages for integrated social and economic development.', 'Integrated development funding and convergence for adopted villages', 'Villages adopted under the scheme', 'https://saanjhi.gov.in'],

  // ── BUSINESS, MSME & ENTREPRENEURSHIP ─────────────────────────────────────
  ['zed-certification', 'ZED – Zero Defect Zero Effect Certification', 'Business', 'MSME Quality', 'Certification framework encouraging MSMEs to manufacture quality products with zero environmental effect.', 'Subsidised certification and incentives for MSMEs', 'All registered MSME units', 'https://zed.gov.in'],
  ['startup-india-seed-fund', 'Startup India Seed Fund Scheme', 'Business', 'Startup Funding', 'Financial assistance for proof of concept, prototype development and market entry of startups.', 'Seed funding up to ₹50 Lakh per startup', 'DIPP-recognised startups approved through incubators', 'https://seedfund.startupindia.gov.in'],
  ['fund-of-funds', 'Fund of Funds for Startups (FFS)', 'Business', 'Startup Capital', 'Government-backed fund of funds providing equity capital through SEBI-registered Alternative Investment Funds.', 'Equity investment through AIFs for eligible startups', 'Startups recognised by DIPP', 'https://www.startupindia.gov.in'],
  ['interest-equalisation', 'Interest Equalisation Scheme (IES)', 'Business', 'Export Credit', 'Interest subvention on pre and post shipment rupee export credit for exporters.', 'Interest subvention of 2-3% on export credit', 'Merchant and manufacturer exporters in eligible sectors', 'https://www.rbi.org.in'],
  ['sfurti', 'Scheme of Fund for Regeneration of Traditional Industries (SFURTI)', 'Business', 'Traditional Industry Clusters', 'Regenerates traditional industry clusters of khadi, village industries, honey, bamboo and coir.', 'New equipment, skill development and working capital for clusters', 'Khadi and village industry clusters and artisans', 'https://sfurti.kviconline.gov.in'],
  ['coir-udyami', 'Coir Udyami Yojana', 'Business', 'Coir Workers', 'Provides machinery and working capital assistance to coir workers and entrepreneurs.', 'Subsidy up to 50% on coir machinery projects', 'Coir workers, entrepreneurs and coir cooperatives', 'https://coirboard.gov.in'],
  ['tcsp', 'Technology Centre Systems Programme (TCSP)', 'Business', 'MSME Technology', 'Establishes technology centres providing MSMEs with access to advanced manufacturing technologies.', 'Subsidised technology testing and skill training', 'MSME units and industry professionals', 'https://tcsp.msme.gov.in'],

  // ── DIGITAL, TRANSPORT & COMMUNICATION ────────────────────────────────────
  ['digilocker', 'DigiLocker – Digital Document Wallet', 'Digital', 'Digital Identity', 'Government digital locker for storing and sharing official documents electronically.', 'Free secure storage of documents with Aadhaar-based access', 'All Indian citizens', 'https://www.digilocker.gov.in'],
  ['umang-app', 'UMANG – Unified Mobile App for Government Services', 'Digital', 'Digital Services', 'Single mobile app for accessing over 1,800 government services across central and state departments.', 'Free access to government services on mobile', 'All citizens', 'https://web.umang.gov.in'],
  ['pm-wani', 'PM-WANI – Public Wi-Fi Access Network', 'Digital', 'Internet Access', 'Sets up public Wi-Fi hotspots through local entrepreneurs for affordable internet access.', 'Low-cost public Wi-Fi hotspots', 'All citizens in covered areas', 'https://pmwani.gov.in'],
  ['national-broadband', 'National Broadband Mission', 'Digital', 'Broadband Connectivity', 'Expands broadband coverage to all villages through optical fibre and wireless technologies.', 'Affordable broadband connectivity in rural areas', 'All households in mission-covered villages', 'https://nbm.gov.in'],
  ['pm-ebus', 'PM e-Bus Sewa', 'Transport', 'Electric Buses', 'Deploys electric buses in cities with less than 4 lakh population for clean public transport.', 'Subsidised electric bus operations for citizens', 'Residents of covered cities', 'https://www.ieefa.org'],
  ['pm-edrive', 'PM E-DRIVE – Electric Vehicle Scheme', 'Transport', 'EV Adoption', 'Promotes electric mobility through demand incentives on e-2Ws, e-3Ws, e-buses and charging infrastructure.', 'Purchase subsidies up to ₹50,000 on electric vehicles', 'All citizens purchasing eligible electric vehicles', 'https://www.heavyindustries.gov.in'],
  ['village-connectivity', '4G Mobile Connectivity for Villages', 'Communication', 'Rural Connectivity', 'Extends 4G mobile coverage to uncovered villages including Aspirational Districts.', 'Free/affordable 4G coverage in uncovered villages', 'Residents of notified uncovered villages', 'https://dot.gov.in'],

  // ── SPORTS, CULTURE & TOURISM ─────────────────────────────────────────────
  ['khelo-india', 'Khelo India Programme', 'Sports', 'Sports Development', 'National programme for sports development including talent identification, annual sports competitions and scholarships.', 'Annual sports scholarship of ₹1.25 Lakh for selected athletes', 'Young athletes identified through Khelo India talent hunt', 'https://kheloindia.gov.in'],
  ['tops', 'Target Olympic Podium Scheme (TOPS)', 'Sports', 'Elite Athletes', 'Assists top athletes with world-class coaching, equipment, and international exposure for Olympic medal chances.', 'Fully funded training, equipment and competitions', 'Athletes in the TOPS core group', 'https://sportsauthorityofindia.nic.in'],
  ['ek-bharat', 'Ek Bharat Shreshtha Bharat', 'Culture', 'Cultural Exchange', 'Promotes mutual understanding between states through paired cultural and linguistic exchange programmes.', 'Cultural exchange programmes and language learning', 'All citizens, especially students', 'https://ekbharat.gov.in'],
  ['adopt-heritage', 'Adopt a Heritage Scheme', 'Culture', 'Monument Development', 'Invites private and public entities to adopt monuments for their upkeep, amenities and visitor services.', 'Improved amenities and preservation at adopted monuments', 'Visitors to adopted heritage sites', 'https://adoptaheritage.in'],
  ['swadesh-darshan', 'Swadesh Darshan Scheme', 'Tourism', 'Tourism Circuits', 'Develops theme-based tourist circuits across the country with infrastructure and destination management.', 'Developed tourism infrastructure and facilities', 'Tourists and local communities in circuit areas', 'https://swadeshdarshan.gov.in'],
  ['rashtriya-sanskriti-mahotsav', 'Rashtriya Sanskriti Mahotsav', 'Culture', 'Cultural Festivals', 'Annual cultural festival showcasing art, craft, music and dance of different states.', 'Free public access to cultural performances', 'All citizens', 'https://indiaculture.gov.in'],

  // ── SCIENCE, HEALTH INFRA & MISCELLANEOUS ─────────────────────────────────
  ['inspire', 'INSPIRE – Innovation in Science Pursuit for Inspired Research', 'Science & Technology', 'Science Talent', 'Attracts youth towards science through scholarships, internships and fellowships.', '₹5,000 per month scholarship for science students', 'Top-1% students in science streams at each board level', 'https://www.online-inspire.gov.in'],
  ['namo-drone-didi', 'Namo Drone Didi', 'Women', 'Drone Entrepreneurship', 'Provides drone clusters to women SHGs for agricultural spraying services.', 'Drones and training for women SHG members', 'Women members of rural SHGs selected through NRLM', 'https://nrlm.gov.in'],
  ['panchayat-empowerment', 'National Panchayat Awards Programme', 'Rural Development', 'Panchayat Excellence', 'Rewards best-performing Panchayats across India in local governance and service delivery.', 'Prestige awards and incentive grants for Panchayats', 'All Gram Panchayats', 'https://panchayat.gov.in']
];
