/**
 * West Bengal State Government Welfare Schemes Dataset
 * [external_id, title, category, tag, description, benefit, eligibility, source_url]
 */
export const WB_SCHEMES = [
  // ── WB HEALTHCARE ─────────────────────────────────────────────────────────
  ['wb-gana-swasthya-kendra', 'Gana Swasthya Kendra (WB)', 'Healthcare', 'Primary Health', 'State-funded primary health and wellness centres in every village providing free basic healthcare.', 'Free primary care, medicines and basic diagnostics', 'All residents of West Bengal', 'https://wbhealth.gov.in'],
  ['wb-mamata', 'Mamata Yojana (WB Antenatal)', 'Healthcare', 'Maternal Health', 'Nutritional cash benefit for pregnant and lactating women to reduce maternal and child malnutrition.', '₹1,000 cash incentive for safe delivery and nutrition', 'Pregnant women (19+) of BPL families, first two children', 'https://wbhealth.gov.in'],
  ['wb-nidan', 'Nidan – Free Diagnostics (WB)', 'Healthcare', 'Diagnostics', 'Free diagnostic tests including pathology, radiology and ECG at district hospitals and BPHCs.', 'Free diagnostic tests at public health facilities', 'All patients referred from public facilities', 'https://wbhealth.gov.in'],
  ['wb-108-ambulance', '108 Emergency Ambulance Service (WB)', 'Healthcare', 'Emergency Transport', 'Free emergency ambulance and patient transport across West Bengal through call centre.', 'Free 24x7 emergency ambulance service', 'All residents of West Bengal in emergencies', 'https://www.wbhealth.gov.in'],
  ['wb-janani-express', 'Janani Express (WB)', 'Healthcare', 'Maternal Transport', 'Free referral transport for pregnant women from home to health facility and back.', 'Free door-to-facility transport for delivery', 'Pregnant women in rural West Bengal', 'https://www.wbhealth.gov.in'],
  ['wb-aarogya-bhavan', 'Aarogya Bhawan – Free Medicines', 'Healthcare', 'Free Medicines', 'Supply of free essential medicines from public health facilities for all patients.', 'Free essential medicines at PHCs, BPHCs and hospitals', 'All patients in public facilities', 'https://wbhealth.gov.in'],
  ['wb-rbsk', 'RBSK – Child Health Screening (WB)', 'Healthcare', 'Child Health', 'Free health screening and early intervention for children in schools and anganwadis.', 'Free screening for 30 health conditions', 'Children aged 0-18 in West Bengal', 'https://www.wbhealth.gov.in'],
  ['wb-sickle-cell', 'Sickle Cell Screening (WB Tribal)', 'Healthcare', 'Tribal Health', 'Screening and counselling for sickle cell disease among tribal communities of West Bengal.', 'Free screening, counselling and treatment', 'Tribal community members in WB', 'https://www.wbhealth.gov.in'],
  ['wb-malaria', 'Malaria Free West Bengal', 'Healthcare', 'Vector Control', 'Intensified malaria control with free testing, treatment and bednet distribution.', 'Free testing, treatment and insecticide-treated nets', 'Residents of malaria-prone districts', 'https://www.wbhealth.gov.in'],
  ['wb-ayush', 'AYUSH Dispensary Services (WB)', 'Healthcare', 'AYUSH', 'Free Ayurveda, Unani, Homeopathy and Yoga services at state AYUSH dispensaries.', 'Free AYUSH consultations and medicines', 'All residents of West Bengal', 'https://wbhealth.gov.in'],
  ['wb-jal-shuddhi', 'Safe Drinking Water Testing Camps (WB)', 'Healthcare', 'Water Quality', 'Free water quality testing camps and awareness in arsenic-affected districts.', 'Free water testing and purification support', 'Residents of arsenic-hit districts', 'https://www.wbhealth.gov.in'],
  ['wb-dialysis', 'Free Dialysis in Government Hospitals (WB)', 'Healthcare', 'Dialysis', 'Free dialysis services for kidney patients in state government hospitals.', 'Free dialysis sessions', 'Kidney patients in WB public hospitals', 'https://wbhealth.gov.in'],
  ['wb-mental-health', 'Manasik Swasthya Kendra (WB)', 'Healthcare', 'Mental Health', 'District mental health programme with counselling and treatment facilities.', 'Free counselling and psychiatric services', 'All residents of West Bengal', 'https://www.wbhealth.gov.in'],
  ['wb-nutrition-rehab', 'Nutrition Rehabilitation Centres (WB)', 'Healthcare', 'Child Nutrition', 'Facility-based treatment for severely malnourished children with free therapeutic feeding.', 'Free 14-day therapeutic feeding for SAM children', 'Severely malnourished children under 5', 'https://www.wbhealth.gov.in'],
  ['wb-asha', 'ASHA Worker Support (WB)', 'Healthcare', 'Community Health', 'Community health volunteers providing doorstep maternal, child and family welfare services.', 'Free doorstep health services and referral support', 'All rural households', 'https://www.wbhealth.gov.in'],

  // ── WB EDUCATION & SCHOLARSHIPS ───────────────────────────────────────────
  ['wb-shishu-shiksha', 'Shishu Shiksha Karmasuchi (Kanyashree K1)', 'Education', 'Early Childhood', 'Pre-primary schooling for children aged 4-6 years in anganwadi-cum-schools.', 'Free pre-primary education and nutrition', 'Children aged 4-6 years in West Bengal', 'https://www.wbkanyashree.gov.in'],
  ['wb-svmcm', 'Swami Vivekananda Merit-cum-Means Scholarship', 'Education', 'Higher Education', 'State scholarship for meritorious students from economically weaker families pursuing UG/PG courses.', '₹24,000-48,000 per year depending on course', 'WB domicile students with family income below ₹2.5 Lakh', 'https://svmcm.wb.gov.in'],
  ['wb-aikyashree-pre', 'Aikyashree Pre-Matric Scholarship', 'Education', 'Minority Education', 'State scholarship for minority community students from class I to X.', '₹500-3,000 per year scholarship', 'Minority students (class I-X) in WB', 'https://www.wbmin.org'],
  ['wb-aikyashree-post', 'Aikyashree Post-Matric Scholarship', 'Education', 'Minority Education', 'Post-matric scholarship for minority students pursuing higher education in West Bengal.', '₹5,000-16,000 per year depending on course', 'Minority students (class XI onwards) in WB', 'https://www.wbmin.org'],
  ['wb-aikyashree-mcm', 'Aikyashree Merit-cum-Means Scholarship', 'Education', 'Minority Higher Ed', 'Higher education scholarship for minority students in professional and technical courses.', '₹20,000 per year for professional courses', 'Minority students in technical/professional courses', 'https://www.wbmin.org'],
  ['wb-sabooj-sathi-ix', 'Sabooj Sathi – Bicycle for Class IX', 'Education', 'Student Mobility', 'Free standard bicycles to class IX students to reduce dropout and travel burden.', 'Free bicycle to every class IX student', 'Class IX students of state-aided schools', 'https://www.wb.gov.in'],
  ['wb-sabooj-sathi-xi', 'Sabooj Sathi – Gear Bicycle for Class XI', 'Education', 'Student Mobility', 'Gear bicycles provided to class XI students across West Bengal.', 'Free gear bicycle to every class XI student', 'Class XI students of state-aided schools', 'https://www.wb.gov.in'],
  ['wb-sikshashree', 'Sikshashree – Stipend for Disabled Students', 'Education', 'Disability Education', 'Monthly stipend and assistance for students with disabilities from class I to PG.', '₹600-2,000 per month stipend', 'Students with disabilities in WB institutions', 'https://www.wb.gov.in'],
  ['wb-utkarsh-bangla', 'Utkarsh Bangla', 'Education', 'Vocational Education', 'Vocational training in schools to equip students with employable skills.', 'Free vocational skill training in schools', 'Class IX-XII students of WB schools', 'https://www.wb.gov.in'],
  ['wb-exam-fee-reimbursement', 'Examination Fee Reimbursement (WB)', 'Education', 'Exam Support', 'Full reimbursement of Madhyamik and HS examination fees for SC/ST and minority students.', 'Free examination registration for eligible students', 'SC/ST/minority students appearing in Madhyamik/HS', 'https://www.wb.gov.in'],
  ['wb-paray-shikshalay', 'Paray Shikshalay', 'Education', 'Community Learning', 'Neighbourhood learning centres providing remedial education support to school students.', 'Free remedial classes in localities', 'School students needing academic support', 'https://www.wb.gov.in'],
  ['wb-adarsha-vidyalaya', 'Adarsha Vidyalaya (Residential for SC)', 'Education', 'SC Residential', 'Residential schools for meritorious SC students from class V to XII.', 'Free residential schooling for SC students', 'SC students in SC-dominated blocks', 'https://anagrasarkalyan.gov.in'],
  ['wb-netaji-residential', 'Netaji Subhas Residential School', 'Education', 'Residential School', 'State residential schools for meritorious students from economically weaker sections.', 'Free residential education for meritorious students', 'Students from EWS families in WB', 'https://www.wb.gov.in'],
  ['wb-scholarship-it', 'Mukhyamantri Medhabi Chhatra Protsahan', 'Education', 'Merit Scholarship', 'One-time assistance to meritorious students from poor families securing high marks in Madhyamik/HS.', '₹5,000-10,000 one-time assistance', 'Students from poor families with high board scores', 'https://www.wb.gov.in'],
  ['wb-haj-subsidy', 'Haj Subsidy Support (WB)', 'Education', 'Religious Travel', 'Financial assistance to Haj pilgrims from economically weaker sections.', 'Subsidy on Haj travel expenses', 'Haj applicants from EWS families', 'https://www.wb.gov.in'],
  ['wb-ngo-schools', 'Free Textbooks to Government Schools (WB)', 'Education', 'Free Textbooks', 'Free textbooks to all government and aided school students every academic year.', 'Free full-set textbooks for every student', 'Students of government/aided schools in WB', 'https://www.wb.gov.in'],

  // ── WB WOMEN & CHILD ──────────────────────────────────────────────────────
  ['wb-rupashree', 'Rupashree Prakalpa', 'Women', 'Marriage Assistance', 'One-time financial assistance for marriage of eligible women from economically weaker families.', '₹25,000 one-time marriage grant', 'Women (18+) from EWS families at marriage', 'https://www.wbkanyashree.gov.in'],
  ['wb-kanyashree-k2', 'Kanyashree Prakalpa K2 – Annual Scholarship', 'Women', 'Girl Child', 'Annual scholarship for unmarried girl students aged 13-18 continuing education.', '₹1,000 per year scholarship', 'Unmarried girls aged 13-18 in education/skill training', 'https://www.wbkanyashree.gov.in'],
  ['wb-kanyashree-k3', 'Kanyashree Prakalpa K3 – One-time Grant', 'Women', 'Girl Child', 'One-time grant for unmarried girls aged 18+ pursuing higher education or vocational training.', '₹25,000 one-time grant', 'Girls aged 18+ unmarried pursuing education/skill', 'https://www.wbkanyashree.gov.in'],
  ['wb-lakshmir-bhandar', 'Lakshmir Bhandar', 'Women', 'Monthly Assistance', 'Monthly cash assistance to women heads of households for financial independence.', '₹1,000 per month (SC/ST & general), ₹1,200 (Antyodaya)', 'Women aged 25-60 of WB domicile', 'https://laxmirbhandar.wb.gov.in'],
  ['wb-matrusuraksha', 'Matri Suraksha Sahayata (WB)', 'Women', 'Maternity', 'Additional maternity cash benefit over central schemes for women in West Bengal.', '₹3,000 maternity benefit (first child)', 'Pregnant women (19+) in WB, first child', 'https://www.wbhealth.gov.in'],
  ['wb-girl-child-bond', 'State Girl Child Education Bond', 'Women', 'Girl Child Savings', 'Savings support for girl child education and empowerment in identified districts.', 'Bond support for girl child education', 'Girl children in identified districts', 'https://www.wb.gov.in'],
  ['wb-women-helpline', 'Women Helpline 181 (WB)', 'Women', 'Women Safety', '24x7 helpline for women in distress providing counselling, rescue and referral.', 'Free emergency assistance and counselling', 'All women in West Bengal', 'https://www.wb.gov.in'],
  ['wb-osc', 'One Stop Centre (WB)', 'Women', 'Women Safety', 'Integrated support centres for women affected by violence providing medical, legal and counselling aid.', 'Free shelter, medical and legal assistance', 'Women victims of violence', 'https://www.wb.gov.in'],
  ['wb-mahila-samman', 'State Working Women Hostel (WB)', 'Women', 'Working Women', 'Safe and subsidised hostel accommodation for working women in cities.', 'Subsidised hostel accommodation', 'Working women in urban areas', 'https://www.wb.gov.in'],

  // ── WB SOCIAL SECURITY & PENSIONS ─────────────────────────────────────────
  ['wb-old-age-pension', 'Old Age Pension (WB Social Security)', 'Pension', 'Senior Pension', 'Monthly pension for senior citizens of West Bengal under state social security.', '₹1,000 per month (₹1,500 for 80+)', 'WB residents aged 60+', 'https://www.wb.gov.in'],
  ['wb-widow-pension', 'Widow Pension (WB)', 'Pension', 'Widow Support', 'Monthly pension for widows in West Bengal under social security.', '₹1,000 per month', 'Widows aged 18-59 in WB', 'https://www.wb.gov.in'],
  ['wb-disability-pension', 'Disability Pension (WB)', 'Pension', 'Disability Support', 'Monthly pension for persons with disabilities in West Bengal.', '₹1,000 per month', 'Persons with 40%+ disability aged 18-59', 'https://www.wb.gov.in'],
  ['wb-transgender-pension', 'Taposili Bandhu', 'Pension', 'Transgender Support', 'Monthly allowance for transgender persons of West Bengal for social security.', '₹1,000 per month', 'Transgender persons aged 18-59 in WB', 'https://www.wb.gov.in'],
  ['wb-sneha-spandan', 'Sneha Spandan – Disabled Allowance', 'Social Security', 'Disability Allowance', 'Monthly allowance for unemployed persons with disabilities aged 18-59.', '₹500 per month', 'Unemployed persons with disabilities (18-59)', 'https://www.wb.gov.in'],
  ['wb-farmer-pension', 'Krishak Bandhu – Farmer Pension Support', 'Pension', 'Farmer Support', 'Income support and family assistance for farmers under Krishak Bandhu.', '₹6,000 per year income support + ₹2 Lakh death benefit', 'Landholding farmers of West Bengal', 'https://krishakbandhu.net'],
  ['wb-pension-special', 'Special Assistance for Geriatric Care (WB)', 'Pension', 'Elderly Care', 'Additional support for elderly persons living alone in West Bengal.', 'Additional monthly allowance for destitute elderly', 'Elderly persons (60+) living without family support', 'https://www.wb.gov.in'],
  ['wb-nsfp', 'State Supplementary Pension', 'Pension', 'Top-up Pension', 'State top-up over NSAP pensions to enhance old age, widow and disability pensions.', 'State top-up over central pension', 'NSAP pension beneficiaries in WB', 'https://www.wb.gov.in'],

  // ── WB AGRICULTURE & FARMER SUPPORT ───────────────────────────────────────
  ['wb-krishak-bandhu', 'Krishak Bandhu', 'Agriculture', 'Farmer Income Support', 'Direct income support and death benefit for landholding farmers of West Bengal.', '₹6,000 per year + ₹2 Lakh death benefit to families', 'Landholding farmers of WB (Krishak Bandhu card)', 'https://krishakbandhu.net'],
  ['wb-bangla-shasya-bima', 'Bangla Shasya Bima', 'Agriculture', 'Crop Insurance', 'Free crop insurance for farmers with full state-paid premium covering notified crops.', 'Free crop insurance with state-paid premium', 'All WB farmers growing notified crops', 'https://banglashasyabima.in'],
  ['wb-matasya-bandhu', 'Matasya Bandhu', 'Agriculture', 'Fishermen Support', 'Income support for active fishermen and fish farmers of West Bengal.', '₹12,000 per year income support', 'Active fishermen (18-60) with valid ID card', 'https://www.wb.gov.in'],
  ['wb-banglar-bhoomi', 'Banglar Bhoomi', 'Agriculture', 'Land Records', 'Online land records access with dispute-free title updates and digitised mutation.', 'Online land records, ROR and mutation', 'All landholders of West Bengal', 'https://banglaruchchabharani.gov.in'],
  ['wb-kharif-aid', 'Kharif Input Subsidy (WB)', 'Agriculture', 'Input Subsidy', 'Subsidy on agricultural inputs like seeds, fertilizers and diesel for flood-affected farmers.', 'Subsidised inputs and relief for affected farmers', 'Farmers affected by natural calamities', 'https://www.wb.gov.in'],
  ['wb-agri-clinic', 'Krishak Mitra Kendra', 'Agriculture', 'Farmer Services', 'District-level farmer facilitation centres providing advisory and input support.', 'Free advisory and input facilitation', 'All farmers of West Bengal', 'https://www.wb.gov.in'],
  ['wb-organic', 'Organic Farming Promotion (WB)', 'Agriculture', 'Organic Farming', 'Promotion of organic farming clusters with certification and market linkage.', 'Subsidy for organic conversion and certification', 'Farmer groups in identified clusters', 'https://www.wb.gov.in'],
  ['wb-drip-irrigation', 'State Micro Irrigation Subsidy', 'Agriculture', 'Irrigation', 'State subsidy on drip and sprinkler irrigation systems for small farmers.', 'Additional state subsidy over central on micro-irrigation', 'Small and marginal farmers', 'https://www.wb.gov.in'],
  ['wb-tank-rejuvenation', 'Jalabandhu – Pond Rejuvenation', 'Agriculture', 'Water Harvesting', 'Rejuvenation of village ponds and water bodies for irrigation and pisciculture.', 'Free desilting and renovation of ponds', 'Village ponds identified with community', 'https://www.wb.gov.in'],
  ['wb-mango-mission', 'Horticulture Mission (WB)', 'Agriculture', 'Horticulture', 'State support for mango, banana, pineapple and vegetable cultivation clusters.', 'Subsidy on plantation and horticulture infrastructure', 'Horticulture farmers of WB', 'https://www.wb.gov.in'],
  ['wb-tea-workers', 'Tea Garden Workers Welfare (WB)', 'Agriculture', 'Tea Workers', 'Health, education and housing support for plantation workers of tea gardens.', 'Free health services, education and housing support', 'Registered tea garden workers', 'https://www.wb.gov.in'],
  ['wb-sundarban-agri', 'Sundarban Agriculture Support', 'Agriculture', 'Sundarban Farmers', 'Climate-resilient agriculture support for farmers of Sundarban region.', 'Saline-resistant seeds and farming support', 'Farmers of Sundarban blocks', 'https://sdb.wb.gov.in'],

  // ── WB FOOD & NUTRITION ───────────────────────────────────────────────────
  ['wb-khadya-sathi', 'Khadya Sathi', 'Food Security', 'Ration Support', 'State food security scheme distributing free or subsidised rice to all households.', '5 kg free rice per person per month', 'All ration card households of WB', 'https://www.wb.gov.in'],
  ['wb-santushti', 'Santushti – Meals for Elderly', 'Food Security', 'Elderly Meals', 'Free cooked meals for senior citizens aged 60+ at village level centres.', 'Free daily cooked meal for elderly', 'Senior citizens (60+) in rural areas', 'https://www.wb.gov.in'],
  ['wb-icds-children', 'ICDS Supplementary Nutrition – Children', 'Food Security', 'Child Nutrition', 'Hot cooked meals and take-home rations for children aged 6 months-6 years at anganwadis.', 'Free nutritious meals at anganwadi centres', 'Children aged 6 months-6 years', 'https://www.wb.gov.in'],
  ['wb-icds-pregnant', 'ICDS Supplementary Nutrition – Pregnant Women', 'Food Security', 'Maternal Nutrition', 'Take-home rations and nutrition for pregnant women under ICDS in WB.', 'Free take-home nutrition ration', 'Pregnant women registered at anganwadis', 'https://www.wb.gov.in'],
  ['wb-icds-lactating', 'ICDS Supplementary Nutrition – Lactating Mothers', 'Food Security', 'Lactation Support', 'Nutritional support for lactating mothers for up to 6 months post-delivery.', 'Free take-home nutrition ration', 'Lactating mothers in WB', 'https://www.wb.gov.in'],
  ['wb-icds-adolescent', 'ICDS Nutrition – Adolescent Girls', 'Food Security', 'Adolescent Nutrition', 'Nutritional supplementation for adolescent girls under ICDS.', 'Free iron-folic acid and nutrition support', 'Adolescent girls in anganwadi catchment areas', 'https://www.wb.gov.in'],
  ['wb-bhaat-karjya', 'Annapurna Kitchen (WB)', 'Food Security', 'Community Kitchen', 'Community kitchens providing low-cost meals in urban areas for the poor.', 'Subsidised hot meals at community kitchens', 'Urban poor residents', 'https://www.wb.gov.in'],
  ['wb-poshan', 'Poshan Saptah Campaign (WB)', 'Food Security', 'Nutrition Awareness', 'Nutrition month campaigns with growth monitoring and counselling at anganwadis.', 'Free growth monitoring and nutrition counselling', 'Children and mothers in anganwadi areas', 'https://www.wb.gov.in'],

  // ── WB HOUSING & INFRASTRUCTURE ───────────────────────────────────────────
  ['wb-nijo-griha', 'Nijo Griha Nijo Bhumi', 'Housing', 'Urban Housing', 'Provides land and housing to slum dwellers and landless urban poor in municipal areas.', 'Free land and housing for eligible urban poor', 'Urban slum dwellers with valid residential proof', 'https://www.wb.gov.in'],
  ['wb-pmayg-state', 'PMAY-G State Top-Up (WB)', 'Housing', 'Rural Housing', 'State top-up over central PMAY-G grant for rural housing construction.', 'Additional ₹1.20 Lakh top-up over central grant', 'PMAY-G beneficiaries of WB', 'https://pmayg.nic.in'],
  ['wb-nirmal-bangla', 'Nirmal Bangla', 'Housing', 'Sanitation', 'Open-defecation-free mission with toilet construction and waste management in WB.', 'Toilet incentives and sanitation infrastructure', 'Rural households without toilets', 'https://www.wb.gov.in'],
  ['wb-griha-bandhu', 'Griha Bandhu – BPL Housing Support', 'Housing', 'BPL Housing', 'Housing assistance for BPL families outside PMAY-G coverage.', 'Financial assistance for house construction', 'BPL families without pucca houses', 'https://www.wb.gov.in'],
  ['wb-jal-dhara', 'Jal Dhara – Rural Water Supply', 'Water', 'Drinking Water', 'Rural piped water supply schemes in water-stressed districts of West Bengal.', 'Household piped water connections', 'Rural households in water-stressed districts', 'https://www.wb.gov.in'],
  ['wb-rural-roads', 'State Rural Road Connectivity', 'Rural Development', 'Rural Roads', 'Construction of rural roads connecting villages to market and health facilities.', 'All-weather road connectivity', 'Villages without road connectivity', 'https://www.wb.gov.in'],
  ['wb-griha-pravesh', 'Griha Pravesh Yojana (WB)', 'Housing', 'Homeless Support', 'Assistance for constructing houses for homeless families in rural WB.', 'Housing construction assistance', 'Homeless rural families', 'https://www.wb.gov.in'],

  // ── WB EMPLOYMENT & SKILL ─────────────────────────────────────────────────
  ['wb-karmasathi', 'Karmasathi', 'Employment', 'Youth Loans', 'Interest-free loans for unemployed youth to start small businesses.', 'Loan up to ₹2 Lakh at 1% interest', 'Unemployed youth (18-45) with business idea', 'https://www.wb.gov.in'],
  ['wb-yuvashree', 'Yuvashree', 'Employment', 'Unemployment Allowance', 'Monthly allowance for educated unemployed youth of West Bengal.', '₹1,500 per month for up to 3 years', 'Unemployed graduates/post-graduates (21-35)', 'https://www.wb.gov.in'],
  ['wb-taruner-swapno', 'Taruner Swapno', 'Employment', 'Self Employment', 'Working capital support for youth setting up micro-enterprises.', '₹50,000-1 Lakh working capital', 'Youth aged 18-40 with enterprise plan', 'https://www.wb.gov.in'],
  ['wb-student-credit-card', 'Student Credit Card', 'Education', 'Education Loans', 'Collateral-free education loans at concessional interest for WB students.', 'Loans up to ₹10 Lakh at 4% interest', 'Students of WB domicile pursuing higher education', 'https://www.wb.gov.in'],
  ['wb-skill-training', 'State Skill Development Mission', 'Employment', 'Skill Training', 'Free vocational and skill training aligned with industry demand across WB districts.', 'Free certified skill training with placement', 'Youth aged 15-45 of WB', 'https://www.wb.gov.in'],
  ['wb-bangla-sahayata', 'Bangla Sahayata Kendra', 'Employment', 'Facilitation', 'One-stop facilitation centres for all citizen services at block level.', 'Free facilitation for certificates and schemes', 'All citizens of West Bengal', 'https://banglasahayata.wb.gov.in'],
  ['wb-jobs-fair', 'State Job Fairs (WB)', 'Employment', 'Placement', 'District-level job fairs connecting job seekers with private and public employers.', 'Free registration and placement in job fairs', 'Job-seeking youth of WB', 'https://www.wb.gov.in'],
  ['wb-e-waste', 'Green Skill Development (WB)', 'Employment', 'Green Jobs', 'Skill training in solar installation, e-waste management and organic farming.', 'Free green-skill certification', 'Rural youth and women', 'https://www.wb.gov.in'],
  ['wb-self-help', 'State SHG Promotion Programme', 'Employment', 'SHG Loans', 'Interest subsidy and capital support for women self-help groups.', 'Interest subsidy on SHG loans', 'Women SHGs in WB', 'https://www.wb.gov.in'],

  // ── WB SC/ST/OBC & MINORITY ───────────────────────────────────────────────
  ['wb-jai-johar', 'Jai Johar', 'Social Justice', 'Tribal Support', 'Monthly honorarium to Scheduled Tribe families of West Bengal.', '₹1,000 per month per ST family', 'ST families in WB (Scheduled Tribe certificate)', 'https://www.wb.gov.in'],
  ['wb-tribal-hostel', 'ST/SC Hostels (WB)', 'Education', 'Hostel Support', 'Hostel facilities for SC/ST students pursuing higher education away from home.', 'Free hostel accommodation and stipend', 'SC/ST students in post-matric courses', 'https://anagrasarkalyan.gov.in'],
  ['wb-tribal-education', 'Janajati Shiksha Protsahan (WB)', 'Education', 'Tribal Education', 'Education support for tribal students including special coaching and bridging.', 'Free coaching and education support', 'Tribal students in WB', 'https://www.wb.gov.in'],
  ['wb-minority-loan', 'WB Minorities Development Corporation Loans', 'Business', 'Minority Loans', 'Concessional loans for minority community members for education and livelihood.', 'Loans at 5-8% interest for minority entrepreneurs', 'Minority community members in WB', 'https://www.wbminorityaffairs.in'],
  ['wb-scdc-loans', 'SC/ST Finance & Development Corporation Loans', 'Business', 'SC/ST Loans', 'Term loans for income generation activities for SC/ST community members.', 'Loans up to ₹10 Lakh at concessional rates', 'SC/ST persons with viable projects', 'https://anagrasarkalyan.gov.in'],
  ['wb-hill-area', 'Hill Area Development Programme (WB)', 'Rural Development', 'Hill Development', 'Infrastructure and livelihood development in Darjeeling and Kalimpong hill areas.', 'Development projects in hill districts', 'Residents of hill areas', 'https://www.wb.gov.in'],
  ['wb-backward-areas', 'Backward Regions Development (WB)', 'Rural Development', 'Backward Areas', 'Targeted development of infrastructure and livelihood in backward blocks.', 'Infrastructure and livelihood projects', 'Residents of backward blocks', 'https://www.wb.gov.in'],
  ['wb-sundarban-board', 'Sundarban Development Board Schemes', 'Rural Development', 'Sundarban Development', 'Integrated development of Sundarban region with housing, drinking water and livelihood.', 'Housing, water, and livelihood projects', 'Residents of Sundarban region', 'https://sdb.wb.gov.in'],
  ['wb-muslim-education', 'Minority Coaching Centres (WB)', 'Education', 'Minority Coaching', 'Free coaching for minority students preparing for competitive examinations.', 'Free competitive exam coaching', 'Minority students in WB', 'https://www.wbminorityaffairs.in'],
  ['wb-obc-welfare', 'OBC Welfare Programmes (WB)', 'Social Justice', 'OBC Support', 'Educational and economic assistance for Other Backward Classes in WB.', 'Scholarships and loan support for OBC', 'OBC community members of WB', 'https://www.wb.gov.in'],
  ['wb-toto-community', 'Special Assistance for PVTG Communities', 'Social Justice', 'PVTG Support', 'Special development support for Particularly Vulnerable Tribal Groups of WB.', 'Livelihood, health and education support', 'Members of PVTG communities', 'https://www.wb.gov.in'],

  // ── WB DISABILITY ─────────────────────────────────────────────────────────
  ['wb-disability-kit', 'Assistive Devices Distribution (WB)', 'Disability', 'Assistive Aids', 'Free distribution of wheelchairs, hearing aids, crutches and assistive devices.', 'Free assistive devices at camps', 'Persons with disabilities in WB', 'https://www.wb.gov.in'],
  ['wb-disability-job', 'Employment Support for Disabled (WB)', 'Disability', 'Employment', 'Placement assistance and self-employment loans for persons with disabilities.', 'Job placement and loan support', 'Persons with disabilities in WB', 'https://www.wb.gov.in'],
  ['wb-disability-card', 'Disability Certificate Camps (WB)', 'Disability', 'Certification', 'Free camps for issuing disability certificates and UDID cards.', 'Free disability certificate and UDID', 'Persons with disabilities without certificates', 'https://www.wb.gov.in'],
  ['wb-adaptive-education', 'Integrated Education for Disabled (WB)', 'Disability', 'Inclusive Education', 'Supports education of children with disabilities in mainstream schools.', 'Learning support and aids for disabled students', 'Children with disabilities in schools', 'https://www.wb.gov.in'],
  ['wb-disability-sports', 'Para Sports Talent Hunt (WB)', 'Disability', 'Para Sports', 'Identification and training of para athletes of West Bengal.', 'Training and sports support for para athletes', 'Athletes with disabilities in WB', 'https://www.wb.gov.in'],

  // ── WB LABOUR & INFORMAL WORKERS ──────────────────────────────────────────
  ['wb-bocw', 'Building & Construction Workers Welfare (WB)', 'Social Security', 'Construction Workers', 'Welfare benefits for registered construction workers including health, education and pension.', 'Health cover, education grant and pension', 'Registered construction workers of WB', 'https://wb.bocw.gov.in'],
  ['wb-domestic-workers', 'Domestic Workers Welfare Board (WB)', 'Social Security', 'Domestic Workers', 'Registration-based welfare benefits for domestic workers of West Bengal.', 'Assistance on registration and welfare schemes', 'Domestic workers in WB', 'https://www.wb.gov.in'],
  ['wb-rickshaw', 'Rickshaw Pullers Welfare (WB)', 'Social Security', 'Rickshaw Pullers', 'Welfare benefits for registered rickshaw and van pullers.', 'Assistance, insurance and welfare support', 'Registered rickshaw pullers', 'https://www.wb.gov.in'],
  ['wb-shramik-bima', 'Unorganised Workers Insurance (WB)', 'Insurance', 'Worker Insurance', 'Accident and life insurance for unorganised workers of West Bengal.', 'Insurance cover at nominal premium', 'Registered unorganised workers', 'https://www.wb.gov.in'],
  ['wb-fish-workers', 'Fisher Workers Welfare (WB)', 'Social Security', 'Fisher Workers', 'Welfare assistance for registered fish workers including insurance and education grants.', 'Insurance and welfare benefits for fish workers', 'Registered fish workers in WB', 'https://www.wb.gov.in'],
  ['wb-wage-workers', 'Wage Earners Assistance (WB)', 'Social Security', 'Wage Workers', 'Assistance for daily wage earners during crisis and medical emergencies.', 'One-time assistance for wage earners', 'Daily wage earners of WB', 'https://www.wb.gov.in'],

  // ── WB FISHERIES & LIVESTOCK ──────────────────────────────────────────────
  ['wb-fish-farm', 'Fish Pond Development Subsidy (WB)', 'Agriculture', 'Pisciculture', 'Subsidy for construction and renovation of fish ponds for fish farming.', '50% subsidy on pond development', 'Fish farmers in WB', 'https://www.wb.gov.in'],
  ['wb-fish-seed', 'Quality Fish Seed Distribution (WB)', 'Agriculture', 'Fish Seed', 'Distribution of quality fish seed at subsidised rates to fish farmers.', 'Subsidised fish fingerlings', 'Registered fish farmers', 'https://www.wb.gov.in'],
  ['wb-dairy-unit', 'Milch Animal Purchase Subsidy (WB)', 'Agriculture', 'Dairy Farming', 'Subsidy on purchase of milch cows and buffaloes for dairy farmers.', '₹15,000-25,000 subsidy per animal', 'Small dairy farmers and SHGs', 'https://www.wb.gov.in'],
  ['wb-goatry', 'Goatry & Piggery Development (WB)', 'Agriculture', 'Small Ruminants', 'Subsidy for goat and pig rearing units for rural households.', 'Subsidy on animal units', 'Rural households and landless farmers', 'https://www.wb.gov.in'],
  ['wb-poultry', 'Backyard Poultry Scheme (WB)', 'Agriculture', 'Poultry', 'Distribution of improved poultry birds to rural households for livelihood.', 'Free improved birds with vaccination', 'Rural households and women SHGs', 'https://www.wb.gov.in'],
  ['wb-vet-camps', 'Free Veterinary Camps (WB)', 'Agriculture', 'Animal Health', 'Free veterinary treatment and vaccination camps across districts.', 'Free veterinary services and vaccines', 'All livestock owners', 'https://www.wb.gov.in'],
  ['wb-piggery-north', 'North Bengal Piggery Mission', 'Agriculture', 'Piggery NE', 'Piggery development programme for North Bengal districts.', 'Subsidy and technical support for piggery', 'Farmers in North Bengal districts', 'https://www.wb.gov.in'],

  // ── WB INDUSTRIES & MSME ──────────────────────────────────────────────────
  ['wb-udyog-sathi', 'Udyog Sathi – Business Services (WB)', 'Business', 'Industry Support', 'Online single window for industrial and business approvals in West Bengal.', 'Online clearances and facilitation', 'Entrepreneurs and industries in WB', 'https://udyogsathi.wb.gov.in'],
  ['wb-khadi', 'Khadi & Village Industries Support (WB)', 'Business', 'Khadi', 'Marketing, credit and training support for khadi and village industries.', 'Working capital and marketing support', 'Khadi artisans and institutions', 'https://www.wb.gov.in'],
  ['wb-handloom', 'Handloom Weavers Support (WB)', 'Business', 'Handloom', 'Financial support, designs and market linkages for handloom weavers.', 'Credit support and design development', 'Handloom weavers in WB', 'https://www.wb.gov.in'],
  ['wb-handicraft', 'Handicraft Cluster Development (WB)', 'Business', 'Handicrafts', 'Cluster development for terracotta, Dokra, conch shell and other crafts.', 'Infrastructure and marketing for craft clusters', 'Handicraft artisans in WB', 'https://www.wb.gov.in'],
  ['wb-silk', 'Silk Development Programme (WB)', 'Business', 'Sericulture', 'Mulberry and tussar silk development with free rearing support.', 'Subsidy on silkworm rearing and seed', 'Sericulture farmers and rearers', 'https://www.wb.gov.in'],
  ['wb-bamboo', 'Bamboo Development Programme (WB)', 'Business', 'Bamboo', 'Bamboo plantation and value-added craft development.', 'Subsidy on bamboo plantation and processing', 'Bamboo growers and artisans', 'https://www.wb.gov.in'],
  ['wb-startup', 'WB Startup Policy Support', 'Business', 'Startups', 'Seed funding and incubation support for startups registered in West Bengal.', 'Seed fund up to ₹25 Lakh for startups', 'Registered startups in WB', 'https://startupwb.gov.in'],
  ['wb-women-enterprise', 'Women Enterprise Development (WB)', 'Business', 'Women Business', 'Loans and training for women entrepreneurs under state MSME programmes.', 'Concessional loans for women enterprises', 'Women entrepreneurs of WB', 'https://www.wb.gov.in'],

  // ── WB SPORTS, CULTURE & TOURISM ──────────────────────────────────────────
  ['wb-ekalavya', 'Banglar Ekalavya', 'Sports', 'Sports Talent', 'State support for sporting talents with equipment, coaching and stipend.', '₹4,000-8,000 per month stipend for athletes', 'WB athletes identified by sports department', 'https://sports.wb.gov.in'],
  ['wb-gramin-khel', 'Rural Games Initiative (WB)', 'Sports', 'Community Sports', 'Promotion of traditional rural sports through block-level competitions.', 'Sports infrastructure and competitions', 'Rural youth of WB', 'https://sports.wb.gov.in'],
  ['wb-sports-infra', 'Sports Infrastructure Grant (WB)', 'Sports', 'Infrastructure', 'Grants for developing playgrounds, stadiums and indoor sports facilities.', 'Grants for sports infrastructure', 'Municipalities, panchayats and clubs', 'https://sports.wb.gov.in'],
  ['wb-tourism', 'State Tourism Circuit Development', 'Tourism', 'Tourism', 'Development of heritage, eco and rural tourism circuits across WB.', 'Developed tourism facilities', 'Tourists and local communities', 'https://wbtourism.gov.in'],
  ['wb-culture-grant', 'Cultural Organisation Grant (WB)', 'Culture', 'Arts Support', 'Financial support to cultural organisations for performances and festivals.', 'Grants for cultural programmes', 'Registered cultural organisations', 'https://www.wb.gov.in'],
  ['wb-rabindra', 'Rabindra Jayanti Programmes (WB)', 'Culture', 'Heritage', 'Support for programmes promoting Bengali culture, literature and heritage.', 'Event support and cultural scholarships', 'Cultural institutions and artists', 'https://www.wb.gov.in'],

  // ── WB URBAN & MUNICIPAL ──────────────────────────────────────────────────
  ['wb-street-vendor', 'Street Vendor Welfare (WB)', 'Urban Development', 'Vendors', 'ID cards, credit linkage and insurance for street vendors of WB.', 'Credit and insurance for registered vendors', 'Street vendors with vendor IDs', 'https://www.wb.gov.in'],
  ['wb-urban-mission', 'Urban Livelihood Mission (WB State)', 'Urban Development', 'Urban Livelihood', 'Skill and credit support for urban poor households.', 'Skill training and loan linkage', 'Urban poor households', 'https://www.wb.gov.in'],
  ['wb-municipal-health', 'Municipal Health Camps (WB)', 'Healthcare', 'Urban Health', 'Free health check-up camps in urban slum areas of municipalities.', 'Free health camps and medicines', 'Urban slum residents', 'https://www.wb.gov.in'],
  ['wb-slum-development', 'Slum Development Programme (WB)', 'Urban Development', 'Slum Upgradation', 'Infrastructure upgradation of slums including roads, drainage and water.', 'Slum infrastructure development', 'Slum-dwelling communities', 'https://www.wb.gov.in'],

  // ── WB ENERGY & ENVIRONMENT ───────────────────────────────────────────────
  ['wb-solar-home', 'Solar Home Lighting (WB)', 'Energy', 'Solar Homes', 'Subsidised solar home lighting systems for off-grid households.', 'Subsidy on solar home systems', 'Households without grid connection', 'https://www.wb.gov.in'],
  ['wb-green-bangla', 'Green Bengal Mission', 'Environment', 'Plantation', 'Massive tree plantation drives across districts for environmental sustainability.', 'Free saplings and plantation support', 'All citizens and institutions', 'https://www.wb.gov.in'],
  ['wb-water-body', 'Water Body Restoration (WB)', 'Environment', 'Water Bodies', 'Restoration of derelict water bodies for community use and recharge.', 'Restoration support for water bodies', 'Local bodies and communities', 'https://www.wb.gov.in'],
  ['wb-e-bus', 'Electric Bus Fleet (WB)', 'Transport', 'Green Transport', 'Electric bus operations in urban centres of West Bengal for clean transport.', 'Affordable e-bus travel', 'Urban commuters', 'https://transport.wb.gov.in'],

  // ── WB MISCELLANEOUS CITIZEN SERVICES ─────────────────────────────────────
  ['wb-e-district', 'e-District Services (WB)', 'Digital', 'Certificates', 'Online issue of certificates including income, caste, residence and domicile.', 'Free online certificates', 'All citizens of West Bengal', 'https://edistrict.wb.gov.in'],
  ['wb-farmer-card', 'Farmer Card & Krishak Bandhu ID', 'Agriculture', 'Farmer ID', 'Unique ID for farmers enabling scheme benefits and digital records.', 'Krishak Bandhu ID for scheme access', 'All farmers of WB', 'https://krishakbandhu.net'],
  ['wb-gas-connection', 'Pradhan Mantri Ujjwala State Top-Up (WB)', 'Women', 'Clean Cooking', 'State support for LPG connections beyond central Ujjwala coverage.', 'Assistance for LPG connection', 'Eligible BPL women not covered centrally', 'https://www.wb.gov.in'],
  ['wb-amta', 'Amta Model – Rural Livelihood (WB)', 'Rural Development', 'Livelihood', 'Integrated livelihood development model adopted across districts.', 'Livelihood projects and convergence', 'Rural households in model blocks', 'https://www.wb.gov.in'],
  ['wb-fisheries-id', 'Fishermen Identity Card (WB)', 'Agriculture', 'Fisher ID', 'Identity cards for active fishermen enabling scheme benefits.', 'ID card and scheme access', 'Active fishermen of WB', 'https://www.wb.gov.in'],
  ['wb-ration-fair', 'Fair Price Shop Modernisation (WB)', 'Food Security', 'Ration Access', 'Modernisation of fair price shops with electronic point of sale devices.', 'Smooth ration access at fair price shops', 'Ration card holders', 'https://www.wb.gov.in']
];
